export const AUTOLOGIN_REQUEST = '[AUTOLOGIN] AUTOLOGIN_REQUEST';
export const AUTOLOGIN_SUCCESS = '[AUTOLOGIN] AUTOLOGIN_SUCCESS';
export const AUTOLOGIN_FAILED = '[AUTOLOGIN] AUTOLOGIN_FAILED';
export const AUTOLOGIN_IN_PROGRESS = '[AUTOLOGIN] AUTOLOGIN_IN_PROGRESS';
