export const BADRPICKER_REQUEST = '[BADRPICKER] BADRPICKER_REQUEST';
export const BADRPICKER_SUCCESS = '[BADRPICKER] BADRPICKER_SUCCESS';
export const BADRPICKER_FAILED = '[BADRPICKER] BADRPICKER_FAILED';
export const BADRPICKER_IN_PROGRESS = '[BADRPICKER] BADRPICKER_IN_PROGRESS';
export const BADRPICKER_INIT = '[BADRPICKER] BADRPICKER_INIT';


export const BADRPICKER_CHECKER_REQUEST = '[BADRPICKER_CHECKER] BADRPICKER_CHECKER_REQUEST';
export const BADRPICKER_CHECKER_SUCCESS = '[BADRPICKER_CHECKER] BADRPICKER_CHECKER_SUCCESS';
export const BADRPICKER_CHECKER_FAILED = '[BADRPICKER_CHECKER] BADRPICKER_CHECKER_FAILED';
export const BADRPICKER_CHECKER_IN_PROGRESS = '[BADRPICKER_CHECKER] BADRPICKER_CHECKER_IN_PROGRESS';
export const BADRPICKER_CHECKER_INIT = '[BADRPICKER_CHECKER] BADRPICKER_CHECKER_INIT';
