export const CRUD_CREATE = '[CRUD_DATATABLE] CRUD_CREATE';

export const CRUD_SHOW_CREATE = '[CRUD_DATATABLE] CRUD_SHOW_CREATE';

export const CRUD_SHOW_UPDATE = '[CRUD_DATATABLE] CRUD_SHOW_UPDATE';

export const CRUD_SYNC = '[CRUD_DATATABLE] CRUD_SYNC';

export const CRUD_UPDATE = '[CRUD_DATATABLE] CRUD_UPDATE';

export const CRUD_DELETE = '[CRUD_DATATABLE] CRUD_DELETE';

export const CRUD_INIT_REQUEST = '[CRUD_DATATABLE] CRUD_INIT';

export const CRUD_SAVE_ALL_REQUEST = '[CRUD_DATATABLE] CRUD_SAVE_ALL';
