export const AUTH_LOGIN_REQUEST = '[AUTH] AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = '[AUTH] AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = '[AUTH] AUTH_LOGIN_FAILED';
export const AUTH_LOGIN_IN_PROGRESS = '[AUTH] AUTH_LOGIN_IN_PROGRESS';
export const LOGIN_INIT = '[AUTH] LOGIN_INIT';

export const AUTH_LOGOUT_REQUEST = '[AUTH_LOGOUT] AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_IN_PROGRESS = '[AUTH_LOGOUT] AUTH_LOGOUT_IN_PROGRESS';
export const AUTH_LOGOUT_SUCCESS = '[AUTH_LOGOUT] AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILED = '[AUTH_LOGOUT] AUTH_LOGOUT_FAILED';

export const AUTH_CLEAR_CACHE_OBJECTS_REQUEST = '[AUTH_CLEAR_CACHE_OBJECTS] AUTH_CLEAR_CACHE_OBJECTS_REQUEST';
export const AUTH_CLEAR_CACHE_OBJECTS_IN_PROGRESS = '[AUTH_CLEAR_CACHE_OBJECTS] AUTH_CLEAR_CACHE_OBJECTS_IN_PROGRESS';
export const AUTH_CLEAR_CACHE_OBJECTS_SUCCESS = '[AUTH_CLEAR_CACHE_OBJECTS] AUTH_CLEAR_CACHE_OBJECTS_SUCCESS';
export const AUTH_CLEAR_CACHE_OBJECTS_FAILED = '[AUTH_CLEAR_CACHE_OBJECTS] AUTH_CLEAR_CACHE_OBJECTS_FAILED';

export const CHECK_VERSION_REQUEST = '[CHECK_VERSION] CHECK_VERSION_REQUEST';
export const CHECK_VERSION_IN_PROGRESS =
    '[CHECK_VERSION] CHECK_VERSION_IN_PROGRESS';
export const CHECK_VERSION_SUCCESS = '[CHECK_VERSION] CHECK_VERSION_SUCCESS';
export const CHECK_VERSION_FAILED = '[CHECK_VERSION] CHECK_VERSION_FAILED';

