export const INIT_CONSULTATION_DUM_REQUEST =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_REQUEST';
export const INIT_CONSULTATION_DUM_SUCCESS =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_SUCCESS';
export const INIT_CONSULTATION_DUM_FAILED =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_FAILED';
export const INIT_CONSULTATION_DUM_IN_PROGRESS =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_IN_PROGRESS';
export const INIT_CONSULTATION_DUM_INIT =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_INIT';

export const GENERIC_DED_REQUEST = '[GENERIC] GENERIC_DED_REQUEST';
export const GENERIC_DED_SUCCESS = '[GENERIC] GENERIC_DED_SUCCESS';
export const GENERIC_DED_FAILED = '[GENERIC] GENERIC_DED_FAILED';
export const GENERIC_DED_IN_PROGRESS = '[GENERIC] GENERIC_DED_IN_PROGRESS';
export const GENERIC_DED_INIT = '[GENERIC] GENERIC_DED_INIT';
