export const INIT_CONSULTATION_DUM_REQUEST =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_REQUEST';
export const INIT_CONSULTATION_DUM_SUCCESS =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_SUCCESS';
export const INIT_CONSULTATION_DUM_FAILED =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_FAILED';
export const INIT_CONSULTATION_DUM_IN_PROGRESS =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_IN_PROGRESS';
export const INIT_CONSULTATION_DUM_INIT =
  '[INIT_CONSULTATION_DUM] INIT_CONSULTATION_DUM_INIT';

export const GENERIC_DED_REQUEST = '[GENERIC] GENERIC_DED_REQUEST';
export const GENERIC_DED_SUCCESS = '[GENERIC] GENERIC_DED_SUCCESS';
export const GENERIC_DED_FAILED = '[GENERIC] GENERIC_DED_FAILED';
export const GENERIC_DED_IN_PROGRESS = '[GENERIC] GENERIC_DED_IN_PROGRESS';
export const GENERIC_DED_INIT = '[GENERIC] GENERIC_DED_INIT';

export const CONFIRMER_CERTIFICAT_RECEPTION_REQUEST =
  '[CONFIRMER_CERTIFICAT_RECEPTION] CONFIRMER_CERTIFICAT_RECEPTION_REQUEST';
export const CONFIRMER_CERTIFICAT_RECEPTION_SUCCESS =
  '[CONFIRMER_CERTIFICAT_RECEPTION] CONFIRMER_CERTIFICAT_RECEPTION_SUCCESS';
export const CONFIRMER_CERTIFICAT_RECEPTION_FAILED =
  '[CONFIRMER_CERTIFICAT_RECEPTION] CONFIRMER_CERTIFICAT_RECEPTION_FAILED';
export const CONFIRMER_CERTIFICAT_RECEPTION_IN_PROGRESS =
  '[CONFIRMER_CERTIFICAT_RECEPTION] CONFIRMER_CERTIFICAT_RECEPTION_IN_PROGRESS';
export const CONFIRMER_CERTIFICAT_RECEPTION_INIT =
  '[CONFIRMER_CERTIFICAT_RECEPTION] CONFIRMER_CERTIFICAT_RECEPTION_INIT';

  
  export const CALCULER_DELAI_TRANSIT_REQUEST =
  '[CALCULER_DELAI_TRANSIT] CALCULER_DELAI_TRANSIT_REQUEST';
  export const CALCULER_DELAI_TRANSIT_SUCCESS =
  '[CALCULER_DELAI_TRANSIT] CALCULER_DELAI_TRANSIT_SUCCESS';
  export const CALCULER_DELAI_TRANSIT_FAILED =
  '[CALCULER_DELAI_TRANSIT] CALCULER_DELAI_TRANSIT_FAILED';
  export const CALCULER_DELAI_TRANSIT_IN_PROGRESS =
  '[CALCULER_DELAI_TRANSIT] CALCULER_DELAI_TRANSIT_IN_PROGRESS';
  export const CALCULER_DELAI_TRANSIT_INIT =
  '[CALCULER_DELAI_TRANSIT] CALCULER_DELAI_TRANSIT_INIT';
  
  export const TRAITER_NUM_RC_REQUEST =
    '[TRAITER_NUM_RC] TRAITER_NUM_RC_REQUEST';
  export const TRAITER_NUM_RC_SUCCESS =
    '[TRAITER_NUM_RC] TRAITER_NUM_RC_SUCCESS';
  export const TRAITER_NUM_RC_FAILED =
    '[TRAITER_NUM_RC] TRAITER_NUM_RC_FAILED';
  export const TRAITER_NUM_RC_IN_PROGRESS =
    '[TRAITER_NUM_RC] TRAITER_NUM_RC_IN_PROGRESS';
  export const TRAITER_NUM_RC_INIT =
    '[TRAITER_NUM_RC] TRAITER_NUM_RC_INIT';
