
export const ETAT_CHARGEMENT_REQUEST =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_REQUEST';
export const ETAT_CHARGEMENT_SUCCESS =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_SUCCESS';
export const ETAT_CHARGEMENT_FAILED =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_FAILED';
export const ETAT_CHARGEMENT_IN_PROGRESS =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_IN_PROGRESS';
export const ETAT_CHARGEMENT_INIT =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_INIT';

export const HISTORIQUE_ETAT_CHARGEMENT_REQUEST =
'[HISTORIQUE_ETAT_CHARGEMENT] HISTORIQUE_ETAT_CHARGEMENT_REQUEST';
export const HISTORIQUE_ETAT_CHARGEMENT_SUCCESS =
'[HISTORIQUE_ETAT_CHARGEMENT] HISTORIQUE_ETAT_CHARGEMENT_SUCCESS';
export const HISTORIQUE_ETAT_CHARGEMENT_FAILED =
'[HISTORIQUE_ETAT_CHARGEMENT] HISTORIQUE_ETAT_CHARGEMENT_FAILED';
export const HISTORIQUE_ETAT_CHARGEMENT_IN_PROGRESS =
'[HISTORIQUE_ETAT_CHARGEMENT] HISTORIQUE_ETAT_CHARGEMENT_IN_PROGRESS';
export const HISTORIQUE_ETAT_CHARGEMENT_INIT =
'[HISTORIQUE_ETAT_CHARGEMENT] HISTORIQUE_ETAT_CHARGEMENT_INIT';

export const VERSIONS_ETAT_CHARGEMENT_REQUEST =
'[VERSIONS_ETAT_CHARGEMENT] VERSIONS_ETAT_CHARGEMENT_REQUEST';
export const VERSIONS_ETAT_CHARGEMENT_SUCCESS =
'[VERSIONS_ETAT_CHARGEMENT] VERSIONS_ETAT_CHARGEMENT_SUCCESS';
export const VERSIONS_ETAT_CHARGEMENT_FAILED =
'[VERSIONS_ETAT_CHARGEMENT] VERSIONS_ETAT_CHARGEMENT_FAILED';
export const VERSIONS_ETAT_CHARGEMENT_IN_PROGRESS =
'[VERSIONS_ETAT_CHARGEMENT] VERSIONS_ETAT_CHARGEMENT_IN_PROGRESS';
export const VERSIONS_ETAT_CHARGEMENT_INIT =
'[VERSIONS_ETAT_CHARGEMENT] VERSIONS_ETAT_CHARGEMENT_INIT';
