
export const ETAT_CHARGEMENT_REQUEST =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_REQUEST';
export const ETAT_CHARGEMENT_SUCCESS =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_SUCCESS';
export const ETAT_CHARGEMENT_FAILED =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_FAILED';
export const ETAT_CHARGEMENT_IN_PROGRESS =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_IN_PROGRESS';
export const ETAT_CHARGEMENT_INIT =
'[ETAT_CHARGEMENT] ETAT_CHARGEMENT_INIT';
