export const DELIVRERMLV_VALIDERMLV_REQUEST =
  '[DELIVRERMLV] VALIDERMLV_REQUEST';
export const DELIVRERMLV_VALIDERMLV_SUCCESS =
  '[DELIVRERMLV] VALIDERMLV_SUCCESS';
export const DELIVRERMLV_VALIDERMLV_FAILED = '[DELIVRERMLV] VALIDERMLV_FAILED';
export const DELIVRERMLV_VALIDERMLV_IN_PROGRESS =
  '[DELIVRERMLV] VALIDERMLV_IN_PROGRESS';
export const DELIVRERMLV_VALIDERMLV_INIT =
  '[DELIVRERMLV] DELIVRERMLV_VALIDERMLV_INIT';

export const DELIVRERMLV_DELIVRERMLV_REQUEST =
  '[DELIVRERMLV] DELIVRERMLV_REQUEST';
export const DELIVRERMLV_DELIVRERMLV_SUCCESS =
  '[DELIVRERMLV] DELIVRERMLV_SUCCESS';
export const DELIVRERMLV_DELIVRERMLV_FAILED =
  '[DELIVRERMLV] DELIVRERMLV_FAILED';
export const DELIVRERMLV_DELIVRERMLV_IN_PROGRESS =
  '[DELIVRERMLV] DELIVRERMLV_IN_PROGRESS';
export const DELIVRERMLV_DELIVRERMLV_INIT =
  '[DELIVRERMLV] DELIVRERMLV_DELIVRERMLV_INIT';

export const DELIVRERMLV_INIT_DELIVRERMLV_REQUEST =
  '[DELIVRERMLV] DELIVRERMLV_INIT_DELIVRERMLV_REQUEST';
export const DELIVRERMLV_INIT_DELIVRERMLV_SUCCESS =
  '[DELIVRERMLV] DELIVRERMLV_INIT_DELIVRERMLV_SUCCESS';
export const DELIVRERMLV_INIT_DELIVRERMLV_FAILED =
  '[DELIVRERMLV] DELIVRERMLV_INIT_RECHERCHEDECLARATION_FAILED';
export const DELIVRERMLV_INIT_DELIVRERMLV_IN_PROGRESS =
  '[DELIVRERMLV] DELIVRERMLV_INIT_DELIVRERMLV_IN_PROGRESS';
export const DELIVRERMLV_INIT_DELIVRERMLV_INIT =
  '[DELIVRERMLV] DELIVRERMLV_INIT_DELIVRERMLV_INIT';
