export const ECI_INIT_APPOSITION_SCELLES_REQUEST = '[APPOSITION] ECI_INIT_APPOSITION_SCELLES_REQUEST';
export const ECI_INIT_APPOSITION_SCELLES_SUCCESS = '[APPOSITION] ECI_INIT_APPOSITION_SCELLES_SUCCESS';
export const ECI_INIT_APPOSITION_SCELLES_FAILED = '[APPOSITION] ECI_INIT_APPOSITION_SCELLES_FAILED';
export const ECI_INIT_APPOSITION_SCELLES_IN_PROGRESS =
  '[APPOSITION] ECI_INIT_APPOSITION_SCELLES_IN_PROGRESS';
export const ECI_INIT_APPOSITION_SCELLES_INIT = '[APPOSITION] ECI_INIT_APPOSITION_SCELLES_INIT';
