export const ACTIFS_CONSULTATION_REQUEST = '[ACTIFS] CONSULTATION_REQUEST';
export const ACTIFS_CONSULTATION_SUCCESS = '[ACTIFS] CONSULTATION_SUCCESS';
export const ACTIFS_CONSULTATION_FAILED = '[ACTIFS] CONSULTATION_FAILED';
export const ACTIFS_CONSULTATION_IN_PROGRESS = '[ACTIFS] CONSULTATION_IN_PROGRESS';
export const ACTIFS_CONSULTATION_INIT = '[ACTIFS] CONSULTATION_INIT';
