export const BADR_APITABLE_REQUEST = '[BADR_APITABLE] BADR_APITABLE_REQUEST';
export const BADR_APITABLE_SUCCESS = '[BADR_APITABLE] BADR_APITABLE_SUCCESS';
export const BADR_APITABLE_FAILED = '[BADR_APITABLE] BADR_APITABLE_FAILED';
export const BADR_APITABLE_IN_PROGRESS = '[BADR_APITABLE] BADR_APITABLE_IN_PROGRESS';
export const BADR_APITABLE_INIT = '[BADR_APITABLE] BADR_APITABLE_INIT';