export const QRCODE_REQUEST = '[QRCODE] QRCODE_REQUEST';
export const QRCODE_SUCCESS = '[QRCODE] QRCODE_SUCCESS';
export const QRCODE_FAILED = '[QRCODE] QRCODE_FAILED';
export const QRCODE_IN_PROGRESS = '[QRCODE] QRCODE_IN_PROGRESS';
export const QRCODE_INIT = '[QRCODE] QRCODE_INIT';