export const PLAQUES_IMM_REQUEST = '[PLAQUES_IMM] PLAQUES_IMM_REQUEST';
export const PLAQUES_IMM_SUCCESS = '[PLAQUES_IMM] PLAQUES_IMM_SUCCESS';
export const PLAQUES_IMM_FAILED = '[PLAQUES_IMM] PLAQUES_IMM_FAILED';
export const PLAQUES_IMM_IN_PROGRESS = '[PLAQUES_IMM] PLAQUES_IMM_IN_PROGRESS';
export const PLAQUES_IMM_INIT = '[PLAQUES_IMM] PLAQUES_IMM_INIT';
