export const AT_MODULE = 'AT';

export const INIT_APUR_INIT = '[INIT_APUR] INIT_APUR_INIT';

export const PREPARE_APUR_CONFIRM =
  '[PREPARE_APUR_CONFIRM] PREPARE_APUR_CONFIRM';
export const PREPARE_APUR_REMOVE = '[PREPARE_APUR_CONFIRM] PREPARE_APUR_REMOVE';

export const CREATE_APUR_CLEAR_MSG =
  '[CREATE_APUR_CLEAR_MSG] CREATE_APUR_CLEAR_MSG';

export const CREATE_APURAUTO_REQUEST =
  '[CREATE_APURAUTO_REQUEST] CREATE_APURAUTO_REQUEST';
