export const CONFIRMATION_ENTREE_ARRIVEE_REQUEST =
  '[COMPONENT] CONFIRMATION_ENTREE_ARRIVEE_REQUEST';
export const CONFIRMATION_ENTREE_ARRIVEE_SUCCESS =
  '[COMPONENT] CONFIRMATION_ENTREE_ARRIVEE_SUCCESS';
export const CONFIRMATION_ENTREE_ARRIVEE_FAILED =
  '[COMPONENT] CONFIRMATION_ENTREE_ARRIVEE_FAILED';
export const CONFIRMATION_ENTREE_ARRIVEE_IN_PROGRESS =
  '[COMPONENT] RECHERCHEREFDUM_IN_PROGRESS';
export const CONFIRMATION_ENTREE_ARRIVEE_INIT =
  '[COMPONENT] CONFIRMATION_ENTREE_ARRIVEE_INIT';