export const ECI_APPOSER_SCELLES_REQUEST = '[APPOSITION] ECI_APPOSER_SCELLES_REQUEST';
export const ECI_APPOSER_SCELLES_SUCCESS = '[APPOSITION] ECI_APPOSER_SCELLES_SUCCESS';
export const ECI_APPOSER_SCELLES_FAILED = '[APPOSITION] ECI_APPOSER_SCELLES_FAILED';
export const ECI_APPOSER_SCELLES_IN_PROGRESS =
  '[APPOSITION] ECI_APPOSER_SCELLES_IN_PROGRESS';
export const ECI_APPOSER_SCELLES_INIT = '[APPOSITION] ECI_APPOSER_SCELLES_INIT';

export const ECI_GET_SCELLES_APPOSEES_REQUEST = '[APPOSITION] ECI_GET_SCELLES_APPOSEES_REQUEST';
export const ECI_GET_SCELLES_APPOSEES_SUCCESS = '[APPOSITION] ECI_GET_SCELLES_APPOSEES_SUCCESS';
export const ECI_GET_SCELLES_APPOSEES_FAILED = '[APPOSITION] ECI_GET_SCELLES_APPOSEES_FAILED';
export const ECI_GET_SCELLES_APPOSEES_IN_PROGRESS =
  '[APPOSITION] ECI_GET_SCELLES_APPOSEES_IN_PROGRESS';
export const ECI_GET_SCELLES_APPOSEES_INIT = '[APPOSITION] ECI_GET_SCELLES_APPOSEES_INIT';

export const ECI_GET_SCELLES_DECLAREES_REQUEST = '[APPOSITION] ECI_GET_SCELLES_DECLAREES_REQUEST';
export const ECI_GET_SCELLES_DECLAREES_SUCCESS = '[APPOSITION] ECI_GET_SCELLES_DECLAREES_SUCCESS';
export const ECI_GET_SCELLES_DECLAREES_FAILED = '[APPOSITION] ECI_GET_SCELLES_DECLAREES_FAILED';
export const ECI_GET_SCELLES_DECLAREES_IN_PROGRESS =
  '[APPOSITION] ECI_GET_SCELLES_DECLAREES_IN_PROGRESS';
export const ECI_GET_SCELLES_DECLAREES_INIT = '[APPOSITION] ECI_GET_SCELLES_DECLAREES_INIT';



