export const INITCONFIRMATIONARRIVEE_REQUEST =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_REQUEST';
export const INITCONFIRMATIONARRIVEE_SUCCESS =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_SUCCESS';
export const INITCONFIRMATIONARRIVEE_FAILED =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_FAILED';
export const INITCONFIRMATIONARRIVEE_IN_PROGRESS =
  '[COMPONENT] RECHERCHEREFDUM_IN_PROGRESS';
export const INITCONFIRMATIONARRIVEE_INIT =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_INIT';

export const INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_REQUEST =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_REQUEST';
export const INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_SUCCESS =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_SUCCESS';
export const INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_FAILED =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_FAILED';
export const INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_IN_PROGRESS =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_IN_PROGRESS';
export const INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_INIT =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_ETATCHARGEMENT_INIT';

export const INITCONFIRMATIONARRIVEE_UPDATE_VO =
  '[COMPONENT] INITCONFIRMATIONARRIVEE_UPDATE_VO';

export const CONFIRMERNTREE_REQUEST = '[ACTION] CONFIRMERNTREE_REQUEST';
export const CONFIRMERNTREE_SUCCESS = '[ACTION] CONFIRMERNTREE_SUCCESS';
export const CONFIRMERNTREE_FAILED = '[ACTION] CONFIRMERNTREE_FAILED';
export const CONFIRMERNTREE_IN_PROGRESS = '[ACTION] CONFIRMERNTREE_IN_PROGRESS';
export const CONFIRMERNTREE_INIT = '[ACTION ] CONFIRMERNTREET_INIT';

export const typeListe = [
  {code: 'etatChargement', libelle: 'Référence Etat de chargement'},
  {code: 'moyenT', libelle: 'Moyen de transport'},
];

export const typeListeAmp = [
  {code: 'immatriculation', libelle: 'Immatriculation'},
  {code: 'numeroAmp', libelle: 'Numéro'},
];
