// constants Recherche declaration Dum
export const INIT_CONTROLE_COMMUN_REQUEST =
  '[INIT_CONTROLE_COMMUN] INIT_CONTROLE_COMMUN_REQUEST';
export const INIT_CONTROLE_COMMUN_SUCCESS =
  '[INIT_CONTROLE_COMMUN] INIT_CONTROLE_COMMUN_SUCCESS';
export const IINIT_CONTROLE_COMMUN_FAILED =
  '[INIT_CONTROLE_COMMUN] IINIT_CONTROLE_COMMUN_FAILED';
export const INIT_CONTROLE_COMMUN_IN_PROGRESS =
  '[INIT_CONTROLE_COMMUN] INIT_CONTROLE_COMMUN_IN_PROGRESS';
export const INIT_CONTROLE_COMMUN_INIT =
  '[INIT_CONTROLE_COMMUN] INIT_CONTROLE_COMMUN_INIT';

// constants récupérer liste declaration Dum
export const LISTDECLARATION_CONTROLE_COMMUN_REQUEST =
  '[LISTDECLARATION_CONTROLE_COMMUN] LISTDECLARATION_CONTROLE_COMMUN_REQUEST';
export const LISTDECLARATION_CONTROLE_COMMUN_SUCCESS =
  '[LISTDECLARATION_CONTROLE_COMMUN] LISTDECLARATION_CONTROLE_COMMUN_SUCCESS';
export const LISTDECLARATION_CONTROLE_COMMUN_FAILED =
  '[LISTDECLARATION_CONTROLE_COMMUN] LISTDECLARATION_CONTROLE_COMMUN_FAILED';
export const LISTDECLARATION_CONTROLE_COMMUN_IN_PROGRESS =
  '[LISTDECLARATION_CONTROLE_COMMUN] LISTDECLARATION_CONTROLE_COMMUN_IN_PROGRESS';
export const LISTDECLARATION_CONTROLE_COMMUN_INIT =
  '[LISTDECLARATION_CONTROLE_COMMUN] LISTDECLARATION_CONTROLE_COMMUN_INIT';

// constants Action VALIDATE SAVE Controle
export const VALIDATESAVE_CONTROLE_COMMUN_REQUEST = '[VALIDATESAVE_CONTROLE_COMMUN] VALIDATESAVE_CONTROLE_COMMUN_REQUEST';
export const VALIDATESAVE_CONTROLE_COMMUN_SUCCESS = '[VALIDATESAVE_CONTROLE_COMMUN] VALIDATESAVE_CONTROLE_COMMUN_SUCCESS';
export const VALIDATESAVE_CONTROLE_COMMUN_FAILED = '[VALIDATESAVE_CONTROLE_COMMUN] VALIDATESAVE_CONTROLE_COMMUN_FAILED';
export const VALIDATESAVE_CONTROLE_COMMUN_IN_PROGRESS =
    '[VALIDATESAVE_CONTROLE_COMMUN] VALIDATESAVE_CONTROLE_COMMUN_IN_PROGRESS';

// constants generer compte rendu Controle
export const GENERERCR_CONTROLE_COMMUN_REQUEST = '[GENERERCR_CONTROLE_COMMUN] GENERERCR_CONTROLE_COMMUN_REQUEST';
export const GENERERCR_CONTROLE_COMMUN_SUCCESS = '[GENERERCR_CONTROLE_COMMUN] GENERERCR_CONTROLE_COMMUN_SUCCESS';
export const GENERERCR_CONTROLE_COMMUN_FAILED = '[GENERERCR_CONTROLE_COMMUN] GENERERCR_CONTROLE_COMMUN_FAILED';
export const GENERERCR_CONTROLE_COMMUN_IN_PROGRESS = '[GENERERCR_CONTROLE_COMMUN] GENERERCR_CONTROLE_COMMUN_IN_PROGRESS';

export const CONTROLE_SET_ERROR_MESSAGE_REQUEST = '[CONTROLE_SET_ERROR_MESSAGE] CONTROLE_SET_ERROR_MESSAGE_REQUEST';

export const CONTROLE_HIDE_REDRESSEMENT_REQUEST = '[CONTROLE_HIDE_REDRESSEMENT] CONTROLE_HIDE_REDRESSEMENT_REQUEST';

export const CONTROLE_UPDATE_VERSIONS_REQUEST = '[CONTROLE_UPDATE_VERSIONS] CONTROLE_UPDATE_VERSIONS_REQUEST';