export const AT_MODULE = 'AT';
export const CODE_TYPE_COMP_VEHICULE = '001';
export const CODE_TYPE_COMP_MOTO_QUAD = '003';
export const SEPAR_ID_VOY = '::';
/*Init Apurement */
export const INIT_APUR_REQUEST = '[INIT_APUR] INIT_APUR_REQUEST';
export const INIT_APUR_SUCCESS = '[INIT_APUR] INIT_APUR_SUCCESS';
export const INIT_APUR_FAILED = '[INIT_APUR] INIT_APUR_FAILED';
export const INIT_APUR_IN_PROGRESS = '[INIT_APUR] INIT_APUR_IN_PROGRESS';
export const INIT_APUR_INIT = '[INIT_APUR] INIT_APUR_INIT';
/*Init Apurement Auto */
export const INIT_APURAUTO_REQUEST = '[INIT_APURAUTO] INIT_APURAUTO_REQUEST';
export const INIT_APURAUTO_SUCCESS = '[INIT_APURAUTO] INIT_APURAUTO_SUCCESS';
export const INIT_APURAUTO_FAILED = '[INIT_APURAUTO] INIT_APURAUTO_FAILED';
export const INIT_APURAUTO_IN_PROGRESS =
  '[INIT_APURAUTO] INIT_APURAUTO_IN_PROGRESS';
export const INIT_APURAUTO_INIT = '[INIT_APURAUTO] INIT_APURAUTO_INIT';

export const PREPARE_APUR_CONFIRM =
  '[PREPARE_APUR_CONFIRM] PREPARE_APUR_CONFIRM';
export const PREPARE_APUR_REMOVE = '[PREPARE_APUR_CONFIRM] PREPARE_APUR_REMOVE';
/*Create Apurement */
export const CREATE_APUR_REQUEST = '[CREATE_APUR_REQUEST] CREATE_APUR_REQUEST';
export const CREATE_APUR_SUCCESS = '[CREATE_APUR_SUCCESS] CREATE_APUR_SUCCESS';
export const CREATE_APUR_FAILED = '[CREATE_APUR_FAILED] CREATE_APUR_FAILED';
export const CREATE_APUR_IN_PROGRESS =
  '[CREATE_APUR_IN_PROGRESS] CREATE_APUR_CLEAR_MSG';
export const CREATE_APUR_CLEAR_MSG =
  '[CREATE_APUR_CLEAR_MSG] CREATE_APUR_CLEAR_MSG';
/*Create Apurement Auto */
export const CREATE_APURAUTO_REQUEST =
  '[CREATE_APURAUTO_REQUEST] CREATE_APURAUTO_REQUEST';
export const CREATE_APURAUTO_SUCCESS =
  '[CREATE_APURAUTO_SUCCESS] CREATE_APURAUTO_SUCCESS';
export const CREATE_APURAUTO_FAILED =
  '[CREATE_APURAUTO_FAILED] CREATE_APURAUTO_FAILED';
export const CREATE_APURAUTO_IN_PROGRESS =
  '[CREATE_APURAUTO_IN_PROGRESS] CREATE_APURAUTO_IN_PROGRESS';
/*Verifier dépassement délai */
export const VERIFIER_DELAI_DEPASSEMENT_SUCCESS =
  '[VERIFIER_DELAI_DEPASSEMENT_SUCCESS] VERIFIER_DELAI_DEPASSEMENT_SUCCESS';
export const VERIFIER_DELAI_DEPASSEMENT_FAILED =
  '[VERIFIER_DELAI_DEPASSEMENT_FAILED] VERIFIER_DELAI_DEPASSEMENT_FAILED';
export const VERIFIER_DELAI_DEPASSEMENT_IN_PROGRESS =
  '[VERIFIER_DELAI_DEPASSEMENT_IN_PROGRESS] VERIFIER_DELAI_DEPASSEMENT_IN_PROGRESS';
export const VERIFIER_DELAI_DEPASSEMENT_REQUEST =
  '[VERIFIER_DELAI_DEPASSEMENT_REQUEST] VERIFIER_DELAI_DEPASSEMENT_REQUEST';
/*Rechrech Multi */
export const RECH_MULTI_REQUEST = '[RECH_MULTI_REQUEST] RECH_MULTI_REQUEST';
export const RECH_MULTI_SUCCESS = '[RECH_MULTI_SUCCESS] RECH_MULTI_SUCCESS';
export const RECH_MULTI_FAILED = '[RECH_MULTI_FAILED] RECH_MULTI_FAILED';
export const RECH_MULTI_IN_PROGRESS =
  '[RECH_MULTI_IN_PROGRESS] RECH_MULTI_IN_PROGRESS';
export const RECH_MULTI_CLEAR_MSG =
  '[RECH_MULTI_CLEAR_MSG] RECH_MULTI_CLEAR_MSG';
export const RECH_MULTI_INIT = '[RECH_MULTI] RECH_MULTI_INIT';
