export const RECHERCHEDUM_INITCONTROLE_REQUEST = '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_REQUEST';
export const RECHERCHEDUM_INITCONTROLE_SUCCESS = '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_SUCCESS';
export const RECHERCHEDUM_INITCONTROLE_FAILED = '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_FAILED';
export const RECHERCHEDUM_INITCONTROLE_IN_PROGRESS = '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_IN_PROGRESS';
export const RECHERCHEDUM_INITCONTROLE_INIT = '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_INIT';