export const RECHERCHEDUM_INITCONTROLE_REQUEST =
  '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_REQUEST';
export const RECHERCHEDUM_INITCONTROLE_SUCCESS =
  '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_SUCCESS';
export const RECHERCHEDUM_INITCONTROLE_FAILED =
  '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_FAILED';
export const RECHERCHEDUM_INITCONTROLE_IN_PROGRESS =
  '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_IN_PROGRESS';
export const RECHERCHEDUM_INITCONTROLE_INIT =
  '[RECHERCHEDUM] RECHERCHEDUM_INITCONTROLE_INIT';
// constants récupérer liste declaration Dum
export const RECHERCHEDUM_LISTDECLARATION_REQUEST =
  '[RECHERCHEDUM] RECHERCHEDUM_LISTDECLARATION_REQUEST';
export const RECHERCHEDUM_LISTDECLARATION_SUCCESS =
  '[RECHERCHEDUM] RECHERCHEDUM_LISTDECLARATION_SUCCESS';
export const RECHERCHEDUM_LISTDECLARATION_FAILED =
  '[RECHERCHEDUM] RECHERCHEDUM_LISTDECLARATION_FAILED';
export const RECHERCHEDUM_LISTDECLARATION_IN_PROGRESS =
  '[RECHERCHEDUM] RECHERCHEDUM_LISTDECLARATION_IN_PROGRESS';
export const RECHERCHEDUM_LISTDECLARATION_INIT =
  '[RECHERCHEDUM] RECHERCHEDUM_LISTDECLARATION_INIT';
