export const REGIMEINTERNE_VALIDATESAVE_REQUEST = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_REQUEST';
export const REGIMEINTERNE_VALIDATESAVE_SUCCESS = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_SUCCESS';
export const REGIMEINTERNE_VALIDATESAVE_FAILED = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_FAILED';
export const REGIMEINTERNE_VALIDATESAVE_IN_PROGRESS = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_IN_PROGRESS';