export const REGIMEINTERNE_VALIDATESAVE_REQUEST = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_REQUEST';
export const REGIMEINTERNE_VALIDATESAVE_SUCCESS = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_SUCCESS';
export const REGIMEINTERNE_VALIDATESAVE_FAILED = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_FAILED';
export const REGIMEINTERNE_VALIDATESAVE_IN_PROGRESS = '[REGIMEINTERNE] REGIMEINTERNE_VALIDATESAVE_IN_PROGRESS';
export const REGIMEINTERNE_GENERERCR_REQUEST = '[REGIMEINTERNE] REGIMEINTERNE_GENERERCR_REQUEST';
export const REGIMEINTERNE_GENERERCR_SUCCESS = '[REGIMEINTERNE] REGIMEINTERNE_GENERERCR_SUCCESS';
export const REGIMEINTERNE_GENERERCR_FAILED = '[REGIMEINTERNE] REGIMEINTERNE_GENERERCR_FAILED';
export const REGIMEINTERNE_GENERERCR_IN_PROGRESS = '[REGIMEINTERNE] REGIMEINTERNE_GENERERCR_IN_PROGRESS';