export const REGIMETRANSIT_VALIDATESAVE_REQUEST = '[REGIMETRANSIT] REGIMETRANSIT_VALIDATESAVE_REQUEST';
export const REGIMETRANSIT_VALIDATESAVE_SUCCESS = '[REGIMETRANSIT] REGIMETRANSIT_VALIDATESAVE_SUCCESS';
export const REGIMETRANSIT_VALIDATESAVE_FAILED = '[REGIMETRANSIT] REGIMETRANSIT_VALIDATESAVE_FAILED';
export const REGIMETRANSIT_VALIDATESAVE_IN_PROGRESS = '[REGIMETRANSIT] REGIMETRANSIT_VALIDATESAVE_IN_PROGRESS';
export const REGIMETRANSIT_GENERERCR_REQUEST = '[REGIMETRANSIT] REGIMETRANSIT_GENERERCR_REQUEST';
export const REGIMETRANSIT_GENERERCR_SUCCESS = '[REGIMETRANSIT] REGIMETRANSIT_GENERERCR_SUCCESS';
export const REGIMETRANSIT_GENERERCR_FAILED = '[REGIMETRANSIT] REGIMETRANSIT_GENERERCR_FAILED';
export const REGIMETRANSIT_GENERERCR_IN_PROGRESS = '[REGIMETRANSIT] REGIMETRANSIT_GENERERCR_IN_PROGRESS';