export const REGIMEINTERNE_REQUEST = '[REGIMEINTERNE] REGIMEINTERNE_REQUEST';
export const REGIMEINTERNE_SUCCESS = '[REGIMEINTERNE] REGIMEINTERNE_SUCCESS';
export const REGIMEINTERNE_FAILED = '[REGIMEINTERNE] REGIMEINTERNE_FAILED';
export const REGIMEINTERNE_IN_PROGRESS = '[REGIMEINTERNE] REGIMEINTERNE_IN_PROGRESS';
export const REGIMEINTERNE_INIT = '[REGIMEINTERNE] REGIMEINTERNE_INIT';