export const GENERIC_REQUEST = '[GENERIC] GENERIC_REQUEST';
export const GENERIC_SUCCESS = '[GENERIC] GENERIC_SUCCESS';
export const GENERIC_FAILED = '[GENERIC] GENERIC_FAILED';
export const GENERIC_IN_PROGRESS = '[GENERIC] GENERIC_IN_PROGRESS';
export const GENERIC_INIT = '[GENERIC] GENERIC_INIT';
