export const CO_CONSULTATION_REQUEST =
  '[CO_CONSULTATION] CO_CONSULTATION_REQUEST';
export const CO_CONSULTATION_SUCCESS =
  '[CO_CONSULTATION] CO_CONSULTATION_SUCCESS';
export const CO_CONSULTATION_FAILED =
  '[CO_CONSULTATION] CO_CONSULTATION_FAILED';
export const CO_CONSULTATION_IN_PROGRESS =
  '[CO_CONSULTATION] CO_CONSULTATION_IN_PROGRESS';
export const CO_CONSULTATION_INIT = '[CO_CONSULTATION] CO_CONSULTATION_INIT';
