export const JUSTIF_RETARD_TRANSIT_REQUEST = '[ACTION] JUSTIF_RETARD_TRANSIT_REQUEST';
export const JUSTIF_RETARD_TRANSIT_SUCCESS = '[ACTION] JUSTIF_RETARD_TRANSIT_SUCCESS';
export const JUSTIF_RETARD_TRANSIT_FAILED = '[ACTION] JUSTIF_RETARD_TRANSIT_FAILED';
export const JUSTIF_RETARD_TRANSIT_IN_PROGRESS = '[ACTION] JUSTIF_RETARD_TRANSIT_IN_PROGRESS';
export const JUSTIF_RETARD_TRANSIT_INIT = '[ACTION ] JUSTIF_RETARD_TRANSIT_INIT';

export const INIT_JUSTIF_RETARD_TRANSIT_REQUEST = '[ACTION] INIT_JUSTIF_RETARD_TRANSIT_REQUEST';
export const INIT_JUSTIF_RETARD_TRANSIT_SUCCESS = '[ACTION] INIT_JUSTIF_RETARD_TRANSIT_SUCCESS';
export const INIT_JUSTIF_RETARD_TRANSIT_FAILED = '[ACTION] INIT_JUSTIF_RETARD_TRANSIT_FAILED';
export const INIT_JUSTIF_RETARD_TRANSIT_IN_PROGRESS = '[ACTION] INIT_JUSTIF_RETARD_TRANSIT_IN_PROGRESS';
export const INIT_JUSTIF_RETARD_TRANSIT_INIT = '[ACTION] INIT_JUSTIF_RETARD_TRANSIT_INIT';


