export const ACTIFS_RECHERCHE_REQUEST = '[ACTIFS] RECHERCHE_REQUEST';
export const ACTIFS_RECHERCHE_SUCCESS = '[ACTIFS] RECHERCHE_SUCCESS';
export const ACTIFS_RECHERCHE_FAILED = '[ACTIFS] RECHERCHE_FAILED';
export const ACTIFS_RECHERCHE_IN_PROGRESS = '[ACTIFS] RECHERCHE_IN_PROGRESS';
export const ACTIFS_RECHERCHE_INIT = '[ACTIFS] RECHERCHE_INIT';