export const CONSULTATION_BLE_REQUEST =
  '[CONSULTATION_BLE] CONSULTATION_BLE_REQUEST';
export const CONSULTATION_BLE_SUCCESS =
  '[CONSULTATION_BLE] CONSULTATION_BLE_SUCCESS';
export const CONSULTATION_BLE_FAILED =
  '[CONSULTATION_BLE] CONSULTATION_BLE_FAILED';
export const CONSULTATION_BLE_IN_PROGRESS =
  '[CONSULTATION_BLE] CONSULTATION_BLE_IN_PROGRESS';
export const CONSULTATION_BLE_INIT =
  '[CONSULTATION_BLE] CONSULTATION_BLE_INIT';

export const status = [
  { code: 'ENREGISTRE', libelle: 'Enregistrement'},
];
