export const D17D20_MODULE = 'D17D20';
export const FORMAT_DDMMYYYY_HHMM = 'DD/MM/YYYY HH:mm';

export const INIT_D17_DUM_REQUEST = '[INIT_D17] INIT_D17_DUM_REQUEST';
export const INIT_D17_DUM_SCREEN = '[INIT_D17] INIT_D17_DUM_SCREEN';
export const RECHERCHE_D17_DUM_REQUEST = '[INIT_D17] RECHERCHE_D17_DUM_REQUEST';
export const RECHERCHE_D17_DUM_SUCCESS =
  '[INIT_APUR] RECHERCHE_D17_DUM_SUCCESS';
export const RECHERCHE_D17_DUM_FAILED = '[INIT_APUR] RECHERCHE_D17_DUM_FAILED';
export const RECHERCHE_D17_DUM_IN_PROGRESS =
  '[INIT_APUR] RECHERCHE_D17_DUM_IN_PROGRESS';


// Action for Gestion
export const APUR_CONFIRMER_INIT = '[D17_D20] APUR_CONFIRMER_INIT';
export const APUR_CONFIRMER_REQUEST = '[D17_D20] APUR_CONFIRMER_REQUEST';
export const APUR_CONFIRMER_SUCCESS = '[D17_D20] APUR_CONFIRMER_SUCCESS';
export const APUR_CONFIRMER_FAILED = '[D17_D20] APUR_CONFIRMER_FAILED';
export const APUR_CONFIRMER_IN_PROGRESS = '[D17_D20] APUR_CONFIRMER_IN_PROGRESS';


//ACTION FOR LOT DS

export const AJOUTER_LOT_DS_REQUEST = '[D17_D20] AJOUTER_LOT_DS_REQUEST';
export const AJOUTER_LOT_DS_SUCCESS = '[D17_D20] AJOUTER_LOT_DS_SUCCESS';
export const DELETE_LOT_DS = '[D17_D20] DELETE_LOT_DS';



//ACTION FOR DUM

export const AJOUTER_LIGNE_DUM_REQUEST = '[D17_D20] AJOUTER_LIGNE_DUM_REQUEST';
export const AJOUTER_LIGNE_DUM_SUCCESS = '[D17_D20] AJOUTER_LIGNE_DUM_SUCCESS';
export const DELETE_LIGNE_DUM = '[D17_D20] DELETE_LOT_DUM';

//ACTION FOR EC

export const AJOUTER_LIGNE_EC_REQUEST = '[D17_D20] AJOUTER_LIGNE_EC_REQUEST';
export const AJOUTER_LIGNE_EC_SUCCESS = '[D17_D20] AJOUTER_LIGNE_EC_SUCCESS';
export const DELETE_LIGNE_EC = '[D17_D20] DELETE_LIGNE_EC';


//USE CASE APUREMENT
export const APUR_CONFIRMER_USE_CASE_REQUEST = '[D17_D20] APUR_CONFIRMER_USE_CASE_REQUEST';
export const APUR_CONFIRMER_USE_CASE_SUCCESS = '[D17_D20] APUR_CONFIRMER_USE_CASE_SUCCESS';