export const DTPS_SORTIE_REQUEST =
    '[DTPS_SORTIE] DTPS_SORTIE_REQUEST';
export const DTPS_SORTIE_SUCCESS =
    '[DTPS_SORTIE] DTPS_SORTIE_SUCCESS';
export const DTPS_SORTIE_FAILED =
    '[DTPS_SORTIE] DTPS_SORTIE_FAILED';
export const DTPS_SORTIE_IN_PROGRESS =
    '[DTPS_SORTIE] DTPS_SORTIE_IN_PROGRESS';
export const DTPS_SORTIE_INIT =
    '[DTPS_SORTIE] DTPS_SORTIE_INIT';

export const VALIDER_DTPS_SORTIE_REQUEST =
    '[VALIDER_DTPS_SORTIE] VALIDER_DTPS_SORTIE_REQUEST';
export const VALIDER_DTPS_SORTIE_SUCCESS =
    '[VALIDER_DTPS_SORTIE] VALIDER_DTPS_SORTIE_SUCCESS';
export const VALIDER_DTPS_SORTIE_FAILED =
    '[VALIDER_DTPS_SORTIE] VALIDER_DTPS_SORTIE_FAILED';
export const VALIDER_DTPS_SORTIE_IN_PROGRESS =
    '[VALIDER_DTPS_SORTIE] VALIDER_DTPS_SORTIE_IN_PROGRESS';
export const VALIDER_DTPS_SORTIE_INIT =
    '[VALIDER_DTPS_SORTIE] VALIDER_DTPS_SORTIE_INIT';

    