export const D17D20_MODULE = 'D17D20';

export const INIT_D17_DUM_REQUEST = '[INIT_D17] INIT_D17_DUM_REQUEST';
export const RECHERCHE_D17_DUM_REQUEST = '[INIT_D17] RECHERCHE_D17_DUM_REQUEST';
export const RECHERCHE_D17_DUM_SUCCESS =
  '[INIT_APUR] RECHERCHE_D17_DUM_SUCCESS';
export const RECHERCHE_D17_DUM_FAILED = '[INIT_APUR] RECHERCHE_D17_DUM_FAILED';
export const RECHERCHE_D17_DUM_IN_PROGRESS =
  '[INIT_APUR] RECHERCHE_D17_DUM_IN_PROGRESS';

//Confirmer VuEmbarque
export const VU_EMB_CONFIRMER_REQUEST = 'VU_EMB_CONFIRMER_REQUEST';
export const VU_EMB_CONFIRMER_SUCCESS = ' VU_EMB_CONFIRMER_SUCCESS';
export const VU_EMB_CONFIRMER_FAILED = 'VU_EMB_CONFIRMER_FAILED';
export const VU_EMB_CONFIRMER_IN_PROGRESS =
  'VU_EMB_CONFIRMER_IN_PROGRESS';

//Supprimer VuEmbarque
export const VU_EMB_SUPPRIMER_REQUEST = 'VU_EMB_SUPPRIMER_REQUEST';
export const VU_EMB_SUPPRIMER_SUCCESS = 'VU_EMB_SUPPRIMER_SUCCESS';
export const VU_EMB_SUPPRIMER_FAILED = 'VU_EMB_SUPPRIMER_FAILED';
export const VU_EMB_SUPPRIMER_IN_PROGRESS =
  'VU_EMB_SUPPRIMER_IN_PROGRESS';


export const SCANNER_D17_DUM_INIT = '[INIT_D17] SCANNER_D17_DUM_INIT';
export const SCANNER_D17_DUM_REQUEST = '[INIT_D17] SCANNER_D17_DUM_REQUEST';
export const SCANNER_D17_DUM_SUCCESS = '[INIT_APUR] SCANNER_D17_DUM_SUCCESS';
export const SCANNER_D17_DUM_FAILED = '[INIT_APUR] SCANNER_D17_DUM_FAILED';
export const SCANNER_D17_DUM_IN_PROGRESS = '[INIT_APUR] SCANNER_D17_DUM_IN_PROGRESS';

//VuEmbarque Recherche Liste declaration By ref vehicule
export const VU_EMB_RECH_BY_REF_VH_REQUEST =
  'D17_D20_VU_EMB_RECH_BY_REF_VH_REQUEST';
export const VU_EMB_RECH_BY_REF_VH_SUCCESS =
  '[D17_D20] VU_EMB_RECH_BY_REF_VH_SUCCESS';
export const VU_EMB_RECH_BY_REF_VH_FAILED =
  '[D17_D20] VU_EMB_RECH_BY_REF_VH_FAILED';
export const VU_EMB_RECH_BY_REF_VHN_PROGRESS =
  '[D17_D20] VU_EMB_RECH_BY_REF_VHN_PROGRESS';