module.exports = {
  SERVER_URL: 'https://badr4.douane.gov.ma/badr',
  BACK_OFFICE_BASE_URL: 'https://bomobile-recette.douane.gov.ma/BadrMobile/api',
  LOGIN_API: '/rest/api/login',
  LOGOUT_API: '/rest/api/logout',
  PROCESS_API: '/rest/api/process',
  SEND_STATS: '/action/set',
  SEND_CRASH: '/crashWebService/addCrash',
  TYPE_SERVICE_UC: 'UC',
  TYPE_SERVICE_SP: 'SP',
  MODULE_AT: 'AT',
  MODULE_HAB: 'HAB_LIB',
  MODULE_REF: 'REF_LIB',
  AUTOCOMPLETE_MIN_CHARACTERS: 3,
  AUTOCOMPLETE_LIST_NB_ELEMENTS: -1,
  remote: true,
  bootstrapRoute: 'Home',
};
