export default {
  ecorimport: {
    title: 'Ecor Import',
    ouverture: 'Ouverture',
    cloture: 'Clôture',
    numLigne: 'N° Ligne',
    nbreContenant: 'Nombre contenant',
    agentEcoreur: 'Agent Ecoreur',
    aucunEquipEnleve: 'Aucun Equipement enlevé',
    errorChampsObligatoire: 'Veuillez remplir tous les champs obligatoires (*)',
    declarationDetail: {
      title: 'Déclaration en détail',
      dateHeureEnreg: 'Date heure Enreg',
      typeDed: 'Type DeD',
      operateurDeclarant: 'Opérateur déclarant',
      valeurDeclaree: 'Valeur déclarée',
    },
    mainlevee: {
      title: 'MainLevée',
      dateValidationMainlevee: 'Date Validation',
      dateDelivranceMainlevee: 'Date Délivrance',
      agentValidationMainlevee: 'Agent Validation',
      agentDelivranceMainlevee: 'Agent Délivrance',
      conteneurCibles: 'Conteneurs Ciblés',
      aucun: 'Aucun',
      annotations: 'Annotations',
      avecPesage: 'Aprés pesage',
      avecScanner: 'Avec scanner',
      sansEnceinte: "Sans quitter l'enceinte douanière",
      sousEscorteGend: 'Sous escorte de la Gendarmerie Royale',
      sansEscorteDoua: 'Sans escorte douanières',
      pourEntreposage: 'Pour entreposage',
    },
    bonSortie: {
      bonDeSortie: 'Bon de Sortie',
      nombreColis: 'Nombre colis',
      poidsNet: 'Poids Net',
      delivrePar: 'Délivré par',
      dateHeureBS: 'Date Heure BS',
      immatriculationsVehicules: 'Immatriculations véhicules',
    },
    declarationSommaire: {
      title: 'Déclaration Sommaire',
      typeDeclaration: 'Type déclaration',
      choisirLotDedouanement: 'Choisir Lot dédouanement',
      referenceDeclaration: 'Référence déclaration',
    },
    lotDedouanement: {
      title: 'Lot de dédouanement',
      marque: 'Marque',
    },
    marchandisesEnlevees: {
      title: 'Marchandises Enlevées',
      lieuStockage: 'Lieu du stockage',
      delivrePar: 'Délivré par',
      immatriculationsVehicules: 'Immatriculations véhicules',
      dateHeureEffectiveEnlevement: 'Date heure Effective Enlèvement',
      heureEffectiveEnlevement: 'Heure Effective Enlèvement',
      dateEffectiveEnlevement: 'Date Effective Enlèvement',
    },
    listeEquipementsLot: {
      title: 'Liste des équipements du lot',
      refEquipement: 'Ref. équipement',
      typeEquipement: 'Type équipement',
      tareEquipement: 'Tare équipement',
      dateHeureEnlevement: 'Date Heure Enlèvement',
    },
    popUpListeLotApures: {
      title: 'Liste des lots apurés',
      natureMarchandise: 'Nature marchandise',
      marques: 'Marques',
    },
    enleverMarchandise: {
      title: 'Enlever marchandise',
      numBonSortie: 'Numéro Bon Sortie',
      nombreColis: 'Nombre colis',
      listeEnlevementsEffectues: {
        title: 'Liste des Enlèvements Effectués',
        colis: 'Nombre Colis',
        dateHeureEnlevement: 'Date Heure Enlèvement',
      },
    },
    peserMarchandise: {
      title: 'Peser marchandise',
      listePesagesEffectues: {
        poidsNet: 'Poids Net',
        title: 'Liste des Pesages Effectués',
        dateHeurePesage: 'Date Heure Pesage',
      },
      relevePesage: {
        title: 'Relevé de pesage',
        numPontBascule: 'N° Pont Bascule',
        tares: 'Tares',
        poidsBrut: 'Poids brut',
      },
      errors: {
        poidsBrutIsSupTare: 'Le Poids brût doit être supérieure à la tares',
      },
    },
    enleverMarchandiseParPesage: {
      title: 'Enlever Marchandise par pesage',
    },
    enleverMarchandiseSsManifeste: {
      title: 'Enlever Marchandise sans manifeste',
    },
    verifierPContreEcorSsManifeste: {
      title: 'Vérifier par contre ecor sans manifeste',
    },
    confirmerArriveeSsManifeste: {
      title: 'Confirmer Arivee sans manifeste',
    },
    autoriserAcheminementSsManifeste: {
      title: 'Autoriser Acheminement sans manifeste',
    },
    autoriserAcheminement: {
      title: 'Autorisation Acheminement',
    },
    verifierParContreEcor: {
      title: 'Vérifier par contre ecor',
      dateHeureContreEcor: 'Date Heure Contre Ecor',
      contreEcor: {
        title: 'Contre Ecor',
        dateContreEcor: 'Date contre Ecor',
        dateHeureSorti: 'Date Heure Sortie',
        heureContreEcor: 'Heure contre Ecor',
        numeroPorteSorti: 'Numéro Porte Sortie',
      },

    },
    confirmerArrivee: {
      title: 'Confirmation Arrivée',
    },
    messageConfirmation: {
      title: 'Confirmation',
      content: 'Etes vous sûr de vouloir quitter cette page?',
    },
    scelles: {
      title: 'Scellés',
      mlvScelle: 'Mainlevée-Scellés',
      scellesConfirmationArrivee: 'Scellés confirmation entrée',
      nouveauxScelles: 'Nouveaux scellés',
      oui: 'Oui',
      non: 'Non',
      aucunElement: 'Aucun élément',
      numeroPince: 'Numéro Pince',
      nombreScelles: 'Nombre de Scellés',
      generateurScelle: 'Génerateur de numéros de scellés ',
      numeroScelle: 'Numéro scellé ',
      transporteurExploitantMEAD: 'Transporteur/ Exploitant MEAD',
      choisirValeur: 'Choisir une valeur',
    },
  },
};
