export const AUTOCOMPLETE_REQUEST = '[AUTOCOMPLETE] AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_SUCCESS = '[AUTOCOMPLETE] AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_FAILED = '[AUTOCOMPLETE] AUTOCOMPLETE_FAILED';
export const AUTOCOMPLETE_IN_PROGRESS = '[AUTOCOMPLETE] AUTOCOMPLETE_IN_PROGRESS';
export const AUTOCOMPLETE_INIT = '[AUTOCOMPLETE] AUTOCOMPLETE_INIT';