export const INIT_CONSULTATION_IGTI_REQUEST = '[INIT_CONSULTATION_IGTI] INIT_CONSULTATION_IGTI_REQUEST';
export const INIT_CONSULTATION_IGTI_SUCCESS = '[INIT_CONSULTATION_IGTI] INIT_CONSULTATION_IGTI_SUCCESS';
export const INIT_CONSULTATION_IGTI_FAILED =  '[INIT_CONSULTATION_IGTI] INIT_CONSULTATION_IGTI_FAILED';
export const INIT_CONSULTATION_IGTI_IN_PROGRESS = '[INIT_CONSULTATION_IGTI] INIT_CONSULTATION_IGTI_IN_PROGRESS';
export const INIT_CONSULTATION_IGTI_INIT = '[INIT_CONSULTATION_IGTI] INIT_CONSULTATION_IGTI_INIT';

export const CONSULTATION_IGTI_REQUEST = '[CONSULTATION_IGTI] CONSULTATION_IGTI_REQUEST';
export const CONSULTATION_IGTI_SUCCESS = '[CONSULTATION_IGTI] CONSULTATION_IGTI_SUCCESS';
export const CONSULTATION_IGTI_FAILED = '[CONSULTATION_IGTI] CONSULTATION_IGTI_FAILED';
export const CONSULTATION_IGTI_IN_PROGRESS = '[CONSULTATION_IGTI] CONSULTATION_IGTI_IN_PROGRESS';
export const CONSULTATION_IGTI_INIT = '[CONSULTATION_IGTI] CONSULTATION_IGTI_INIT';
