export const CONFIRMCNX_REQUEST = '[CONFIRMCNX] CONFIRMCNX_REQUEST';
export const CONFIRMCNX_SUCCESS = '[CONFIRMCNX] CONFIRMCNX_SUCCESS';
export const CONFIRMCNX_FAILED = '[CONFIRMCNX] CONFIRMCNX_FAILED';
export const CONFIRMCNX_IN_PROGRESS = '[CONFIRMCNX] CONFIRMCNX_IN_PROGRESS';
export const CONFIRMCNX_INIT = '[CONFIRMCNX] CONFIRMCNX_INIT';