export const T6BIS_INIT_FOR_UPDATE_REQUEST = '[GESTION_T6BIS] T6BIS_INIT_FOR_UPDATE_REQUEST';
export const T6BIS_INIT_FOR_UPDATE_SUCCES = '[GESTION_T6BIS] T6BIS_INIT_FOR_UPDATE_SUCCES';
export const T6BIS_INIT_FOR_UPDATE_FAILED = '[GESTION_T6BIS] T6BIS_INIT_FOR_UPDATE_FAILED';
export const T6BIS_INIT_FOR_UPDATE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_INIT_FOR_UPDATE_IN_PROGRESS';

export const T6BIS_INIT_FOR_REDRESSER_REQUEST = '[GESTION_T6BIS] T6BIS_INIT_FOR_REDRESSER_REQUEST';
export const T6BIS_INIT_FOR_REDRESSER_SUCCES = '[GESTION_T6BIS] T6BIS_INIT_FOR_REDRESSER_SUCCES';
export const T6BIS_INIT_FOR_REDRESSER_FAILED = '[GESTION_T6BIS] T6BIS_INIT_FOR_REDRESSER_FAILED';
export const T6BIS_INIT_FOR_REDRESSER_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_INIT_FOR_REDRESSER_IN_PROGRESS';