export const GENERIC_LIQ_REQUEST = '[GENERIC] GENERIC_LIQ_REQUEST';
export const GENERIC_LIQ_SUCCESS = '[GENERIC] GENERIC_LIQ_SUCCESS';
export const GENERIC_LIQ_FAILED = '[GENERIC] GENERIC_LIQ_FAILED';
export const GENERIC_LIQ_IN_PROGRESS = '[GENERIC] GENERIC_LIQ_IN_PROGRESS';
export const GENERIC_LIQ_INIT = '[GENERIC] GENERIC_LIQ_INIT';
