export const D17D20_MODULE = 'D17D20';

export const RECHERCHE_D17_MAINLEVEE_INIT = 'RECHERCHE_D17_MAINLEVEE_INIT';
export const RECHERCHE_D17_MAINLEVEE_REQUEST = 'RECHERCHE_D17_MAINLEVEE_REQUEST';
export const RECHERCHE_D17_MAINLEVEE_SUCCESS = 'RECHERCHE_D17_MAINLEVEE_SUCCESS';
export const RECHERCHE_D17_MAINLEVEE_FAILED = 'RECHERCHE_D17_MAINLEVEE_FAILED';
export const RECHERCHE_D17_MAINLEVEE_IN_PROGRESS = 'RECHERCHE_D17_MAINLEVEE_IN_PROGRESS';

export const SCANNER_D17_MAINLEVEE_INIT = ' SCANNER_D17_MAINLEVEE_INIT';
export const SCANNER_D17_MAINLEVEE_REQUEST = 'SCANNER_D17_MAINLEVEE_REQUEST';
export const SCANNER_D17_MAINLEVEE_SUCCESS = 'SCANNER_D17_MAINLEVEE_SUCCESS';
export const SCANNER_D17_MAINLEVEE_FAILED = 'SCANNER_D17_MAINLEVEE_FAILED';
export const SCANNER_D17_MAINLEVEE_IN_PROGRESS = 'SCANNER_D17_MAINLEVEE_IN_PROGRESS';

//Confirmer Mainlevee
export const MAINLEVEE_CONFIRMER_REQUEST = '[D17_D20] MAINLEVEE_CONFIRMER_REQUEST';
export const MAINLEVEE_CONFIRMER_SUCCESS = '[D17_D20] MAINLEVEE_CONFIRMER_SUCCESS';
export const MAINLEVEE_CONFIRMER_FAILED = '[D17_D20] MAINLEVEE_CONFIRMER_FAILED';
export const MAINLEVEE_CONFIRMER_IN_PROGRESS = '[D17_D20] MAINLEVEE_CONFIRMER_IN_PROGRESS';
