export const ACTIFS_CREATION_REQUEST = '[ACTIFS] CREATION_REQUEST';
export const ACTIFS_CREATION_SUCCESS = '[ACTIFS] CREATION_SUCCESS';
export const ACTIFS_CREATION_FAILED = '[ACTIFS] CREATION_FAILED';
export const ACTIFS_CREATION_IN_PROGRESS = '[ACTIFS] CREATION_IN_PROGRESS';
export const ACTIFS_CREATION_INIT = '[ACTIFS] CREATION_INIT';
