export const ACTIFS_DETAILS_REQUEST = '[ACTIFS] DETAILS_REQUEST';
export const ACTIFS_DETAILS_SUCCESS = '[ACTIFS] DETAILS_SUCCESS';
export const ACTIFS_DETAILS_FAILED = '[ACTIFS] DETAILS_FAILED';
export const ACTIFS_DETAILS_IN_PROGRESS = '[ACTIFS] DETAILS_IN_PROGRESS';
export const ACTIFS_DETAILS_INIT = '[ACTIFS] DETAILS_INIT';
