export const ACTIFS_ENTETE_REQUEST = '[ACTIFS] ENTETE_REQUEST';
export const ACTIFS_ENTETE_SUCCESS = '[ACTIFS] ENTETE_SUCCESS';
export const ACTIFS_ENTETE_FAILED = '[ACTIFS] ENTETE_FAILED';
export const ACTIFS_ENTETE_IN_PROGRESS = '[ACTIFS] ENTETE_IN_PROGRESS';
export const ACTIFS_ENTETE_INIT = '[ACTIFS] ACTIFS_ENTETE_INIT';
