export const ACTIFS_SAISIE_REQUEST = '[ACTIFS] SAISIE_REQUEST';
export const ACTIFS_SAISIE_SUCCESS = '[ACTIFS] SAISIE_SUCCESS';
export const ACTIFS_SAISIE_FAILED = '[ACTIFS] SAISIE_FAILED';
export const ACTIFS_SAISIE_IN_PROGRESS = '[ACTIFS] SAISIE_IN_PROGRESS';
export const ACTIFS_SAISIE_INIT = '[ACTIFS] SAISIE_INIT';
