export const PRE_CONFIRMATION_ARRIVEE_REQUEST = '[ACTION] PRE_CONFIRMATION_ARRIVEE_REQUEST';
export const PRE_CONFIRMATION_ARRIVEE_SUCCESS = '[ACTION] PRE_CONFIRMATION_ARRIVEE_SUCCESS';
export const PRE_CONFIRMATION_ARRIVEE_FAILED = '[ACTION] PRE_CONFIRMATION_ARRIVEE_FAILED';
export const PRE_CONFIRMATION_ARRIVEE_IN_PROGRESS = '[ACTION] PRE_CONFIRMATION_ARRIVEE_IN_PROGRESS';
export const PRE_CONFIRMATION_ARRIVEE_INIT = '[ACTION ] PRE_CONFIRMATION_ARRIVEE_INIT';

export const INIT_PRE_CONFIRMATION_ARRIVEE_REQUEST = '[ACTION] INIT_PRE_CONFIRMATION_ARRIVEE_REQUEST';
export const INIT_PRE_CONFIRMATION_ARRIVEE_SUCCESS = '[ACTION] INIT_PRE_CONFIRMATION_ARRIVEE_SUCCESS';
export const INIT_PRE_CONFIRMATION_ARRIVEE_FAILED = '[ACTION] INIT_PRE_CONFIRMATION_ARRIVEE_FAILED';
export const INIT_PRE_CONFIRMATION_ARRIVEE_IN_PROGRESS = '[ACTION] INIT_PRE_CONFIRMATION_ARRIVEE_IN_PROGRESS';
export const INIT_PRE_CONFIRMATION_ARRIVEE_INIT = '[ACTION ] INIT_PRE_CONFIRMATION_ARRIVEE_INIT';


