export const T6BIS_INIT_ENTETE_REQUEST = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_REQUEST';
export const T6BIS_INIT_ENTETE_SUCCES = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_SUCCES';
export const T6BIS_INIT_ENTETE_FAILED = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_FAILED';
export const T6BIS_INIT_ENTETE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_IN_PROGRESS';

export const FIND_INTERVENANT_REQUEST = '[GESTION_T6BIS] FIND_INTERVENANT_REQUEST';
export const FIND_INTERVENANT_SUCCES = '[GESTION_T6BIS] FIND_INTERVENANT_SUCCES';
export const FIND_INTERVENANT_FAILED = '[GESTION_T6BIS] FIND_INTERVENANT_FAILED';
export const FIND_INTERVENANT_IN_PROGRESS = '[GESTION_T6BIS] FIND_INTERVENANT_IN_PROGRESS';

export const T6BIS_UPDATE_PROPS_REQUEST = '[GESTION_T6BIS] T6BIS_UPDATE_PROPS_REQUEST';
export const T6BIS_UPDATE_PROPS_SUCCES = '[GESTION_T6BIS] T6BIS_UPDATE_PROPS_SUCCES';
export const T6BIS_UPDATE_PROPS_FAILED = '[GESTION_T6BIS] T6BIS_UPDATE_PROPS_FAILED';
export const T6BIS_UPDATE_PROPS_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_UPDATE_PROPS_IN_PROGRESS';

export const T6BIS_UPDATE_INTERVENANT_REQUEST = '[GESTION_T6BIS] T6BIS_UPDATE_INTERVENANT_REQUEST';
export const T6BIS_UPDATE_INTERVENANT_SUCCES = '[GESTION_T6BIS] T6BIS_UPDATE_INTERVENANT_SUCCES';
export const T6BIS_UPDATE_INTERVENANT_FAILED = '[GESTION_T6BIS] T6BIS_UPDATE_INTERVENANT_FAILED';
export const T6BIS_UPDATE_INTERVENANT_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_UPDATE_INTERVENANT_IN_PROGRESS';


export const T6BIS_GESTION_GET_UNITE_CODE_REQUEST = '[GESTION_T6BIS] T6BIS_GESTION_GET_UNITE_CODE_REQUEST';
export const T6BIS_GESTION_GET_UNITE_CODE_SUCCES = '[GESTION_T6BIS] T6BIS_GESTION_GET_UNITE_CODE_SUCCES';
export const T6BIS_GESTION_GET_UNITE_CODE_FAILED = '[GESTION_T6BIS] T6BIS_GESTION_GET_UNITE_CODE_FAILED';
export const T6BIS_GESTION_GET_UNITE_CODE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_GESTION_GET_UNITE_CODE_IN_PROGRESS';

export const T6BIS_ADD_TAXATION_ARTICLE_REQUEST = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_ARTICLE_REQUEST';
export const T6BIS_ADD_TAXATION_ARTICLE_SUCCES = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_ARTICLE_SUCCES';
export const T6BIS_ADD_TAXATION_ARTICLE_FAILED = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_ARTICLE_FAILED';
export const T6BIS_ADD_TAXATION_ARTICLE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_ARTICLE_IN_PROGRESS';

export const T6BIS_ADD_TAXATION_GLOBALE_REQUEST = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_GLOBALE_REQUEST';
export const T6BIS_ADD_TAXATION_GLOBALE_SUCCES = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_GLOBALE_SUCCES';
export const T6BIS_ADD_TAXATION_GLOBALE_FAILED = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_GLOBALE_FAILED';
export const T6BIS_ADD_TAXATION_GLOBALE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_ADD_TAXATION_GLOBALE_IN_PROGRESS';

export const T6BIS_SAUVEGARDER_REQUEST = '[GESTION_T6BIS] T6BIS_SAUVEGARDER_REQUEST';
export const T6BIS_SAUVEGARDER_SUCCES = '[GESTION_T6BIS] T6BIS_SAUVEGARDER_SUCCES';
export const T6BIS_SAUVEGARDER_FAILED = '[GESTION_T6BIS] T6BIS_SAUVEGARDER_FAILED';
export const T6BIS_SAUVEGARDER_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_SAUVEGARDER_IN_PROGRESS';

export const T6BIS_SUPPRIMER_REQUEST = '[GESTION_T6BIS] T6BIS_SUPPRIMER_REQUEST';
export const T6BIS_SUPPRIMER_SUCCES = '[GESTION_T6BIS] T6BIS_SUPPRIMER_SUCCES';
export const T6BIS_SUPPRIMER_FAILED = '[GESTION_T6BIS] T6BIS_SUPPRIMER_FAILED';
export const T6BIS_SUPPRIMER_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_SUPPRIMER_IN_PROGRESS';

export const T6BIS_ENREGISTRER_REQUEST = '[GESTION_T6BIS] T6BIS_ENREGISTRER_REQUEST';
export const T6BIS_ENREGISTRER_SUCCES = '[GESTION_T6BIS] T6BIS_ENREGISTRER_SUCCES';
export const T6BIS_ENREGISTRER_FAILED = '[GESTION_T6BIS] T6BIS_ENREGISTRER_FAILED';
export const T6BIS_ENREGISTRER_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_ENREGISTRER_IN_PROGRESS';