export const T6BIS_INIT_ENTETE_REQUEST = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_REQUEST';
export const T6BIS_INIT_ENTETE_SUCCES = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_SUCCES';
export const T6BIS_INIT_ENTETE_FAILED = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_FAILED';
export const T6BIS_INIT_ENTETE_IN_PROGRESS = '[GESTION_T6BIS] T6BIS_INIT_ENTETE_IN_PROGRESS';

export const FIND_INTERVENANT_REQUEST = '[GESTION_T6BIS] FIND_INTERVENANT_REQUEST';
export const FIND_INTERVENANT_SUCCES = '[GESTION_T6BIS] FIND_INTERVENANT_SUCCES';
export const FIND_INTERVENANT_FAILED = '[GESTION_T6BIS] FIND_INTERVENANT_FAILED';
export const FIND_INTERVENANT_IN_PROGRESS = '[GESTION_T6BIS] FIND_INTERVENANT_IN_PROGRESS';

