export const INIT_CONSULTATION_TI_REQUEST = '[INIT_CONSULTATION_TI] INIT_CONSULTATION_TI_REQUEST';
export const INIT_CONSULTATION_TI_SUCCESS = '[INIT_CONSULTATION_TI] INIT_CONSULTATION_TI_SUCCESS';
export const INIT_CONSULTATION_TI_FAILED =  '[INIT_CONSULTATION_TI] INIT_CONSULTATION_TI_FAILED';
export const INIT_CONSULTATION_TI_IN_PROGRESS = '[INIT_CONSULTATION_TI] INIT_CONSULTATION_TI_IN_PROGRESS';
export const INIT_CONSULTATION_TI_INIT = '[INIT_CONSULTATION_TI] INIT_CONSULTATION_TI_INIT';

export const CONSULTATION_TI_REQUEST = '[CONSULTATION_TI] CONSULTATION_TI_REQUEST';
export const CONSULTATION_TI_SUCCESS = '[CONSULTATION_TI] CONSULTATION_TI_SUCCESS';
export const CONSULTATION_TI_FAILED = '[CONSULTATION_TI] CONSULTATION_TI_FAILED';
export const CONSULTATION_TI_IN_PROGRESS = '[CONSULTATION_TI] CONSULTATION_TI_IN_PROGRESS';
export const CONSULTATION_TI_INIT = '[CONSULTATION_TI] CONSULTATION_TI_INIT';
