export const INIT_COMPTE_RENDU_REQUEST = '[INIT_COMPTE_RENDU] INIT_COMPTE_RENDU_REQUEST';
export const INIT_COMPTE_RENDU_SUCCESS = '[INIT_COMPTE_RENDU] INIT_COMPTE_RENDU_SUCCESS';
export const INIT_COMPTE_RENDU_FAILED = '[INIT_COMPTE_RENDU] INIT_COMPTE_RENDU_FAILED';
export const INIT_COMPTE_RENDU_IN_PROGRESS = '[INIT_COMPTE_RENDU] INIT_COMPTE_RENDU_IN_PROGRESS';
export const INIT_COMPTE_RENDU_INIT = '[INIT_COMPTE_RENDU] INIT_COMPTE_RENDU_INIT';

export const CONFIRM_COMPTE_RENDU_REQUEST = '[CONFIRM_COMPTE_RENDU] CONFIRM_COMPTE_RENDU_REQUEST';
export const CONFIRM_COMPTE_RENDU_SUCCESS = '[CONFIRM_COMPTE_RENDU] CONFIRM_COMPTE_RENDU_SUCCESS';
export const CONFIRM_COMPTE_RENDU_FAILED = '[CONFIRM_COMPTE_RENDU] CONFIRM_COMPTE_RENDU_FAILED';
export const CONFIRM_COMPTE_RENDU_IN_PROGRESS = '[CONFIRM_COMPTE_RENDU] CONFIRM_COMPTE_RENDU_IN_PROGRESS';
export const CONFIRM_COMPTE_RENDU_INIT = '[CONFIRM_COMPTE_RENDU] CONFIRM_COMPTE_RENDU_INIT';

export const SEARCH_COMPTE_RENDU_REQUEST = '[SEARCH_COMPTE_RENDU] SEARCH_COMPTE_RENDU_REQUEST';
export const SEARCH_COMPTE_RENDU_SUCCESS = '[SEARCH_COMPTE_RENDU] SEARCH_COMPTE_RENDU_SUCCESS';
export const SEARCH_COMPTE_RENDU_FAILED = '[SEARCH_COMPTE_RENDU] SEARCH_COMPTE_RENDU_FAILED';
export const SEARCH_COMPTE_RENDU_IN_PROGRESS = '[SEARCH_COMPTE_RENDU] SEARCH_COMPTE_RENDU_IN_PROGRESS';
export const SEARCH_COMPTE_RENDU_INIT = '[SEARCH_COMPTE_RENDU] SEARCH_COMPTE_RENDU_INIT';
