export const CREATION_T6BIS_ALL_TYPE_REQUEST = '[CREATION_T6BIS] CREATION_T6BIS_ALL_TYPE_REQUEST';
export const CREATION_T6BIS_ALL_TYPE_SUCCES = '[CREATION_T6BIS] CREATION_T6BIS_ALL_TYPE_SUCCES';
export const CREATION_T6BIS_ALL_TYPE_FAILED = '[CREATION_T6BIS] CREATION_T6BIS_ALL_TYPE_FAILED';
export const CREATION_T6BIS_ALL_TYPE_IN_PROGRESS = '[CREATION_T6BIS] CREATION_T6BIS_ALL_TYPE_IN_PROGRESS';

