export const CONSULTATION_BLS_REQUEST =
  '[CONSULTATION_BLS] CONSULTATION_BLS_REQUEST';
export const CONSULTATION_BLS_SUCCESS =
  '[CONSULTATION_BLS] CONSULTATION_BLS_SUCCESS';
export const CONSULTATION_BLS_FAILED =
  '[CONSULTATION_BLS] CONSULTATION_BLS_FAILED';
export const CONSULTATION_BLS_IN_PROGRESS =
  '[CONSULTATION_BLS] CONSULTATION_BLS_IN_PROGRESS';
export const CONSULTATION_BLS_INIT =
  '[CONSULTATION_BLS] CONSULTATION_BLS_INIT';

export const status = [
  { code: 'ENREGISTRE', libelle: 'Enregistrement'},
];
