export const INIT_AUTORISER_ACHEMINEMENT_REQUEST =
  '[COMPONENT] INIT_AUTORISER_ACHEMINEMENT_REQUEST';
export const INIT_AUTORISER_ACHEMINEMENT_SUCCESS =
  '[COMPONENT] INIT_AUTORISER_ACHEMINEMENT_SUCCESS';
export const INIT_AUTORISER_ACHEMINEMENT_FAILED =
  '[COMPONENT] INIT_AUTORISER_ACHEMINEMENT_FAILED';
export const INIT_AUTORISER_ACHEMINEMENT_IN_PROGRESS =
  '[COMPONENT] RECHERCHEREFDUM_IN_PROGRESS';



