export const RECHERCHEREFDUM_REQUEST = '[COMPONENT] RECHERCHEREFDUM_REQUEST';
export const RECHERCHEREFDUM_SUCCESS = '[COMPONENT] RECHERCHEREFDUM_SUCCESS';
export const RECHERCHEREFDUM_FAILED = '[COMPONENT] RECHERCHEREFDUM_FAILED';
export const RECHERCHEREFDUM_IN_PROGRESS =
  '[COMPONENT] RECHERCHEREFDUM_IN_PROGRESS';
export const RECHERCHEREFDUM_INIT = '[COMPONENT] RECHERCHEREFDUM_INIT';
