export const GENERIC_ECI_REQUEST = '[GENERIC] GENERIC_ECI_REQUEST';
export const GENERIC_ECI_SUCCESS = '[GENERIC] GENERIC_ECI_SUCCESS';
export const GENERIC_ECI_FAILED = '[GENERIC] GENERIC_ECI_FAILED';
export const GENERIC_ECI_IN_PROGRESS = '[GENERIC] GENERIC_ECI_IN_PROGRESS';
export const GENERIC_ECI_INIT = '[GENERIC] GENERIC_ECI_INIT';

export const GENERIC_OPEN_MODAL = '[GENERIC] OPEN_MODAL';
export const GENERIC_CLOSE_MODAL = '[GENERIC] CLOSE_MODAL';
