export const DTPS_ENTREE_REQUEST =
    '[DTPS_ENTREE] DTPS_ENTREE_REQUEST';
export const DTPS_ENTREE_SUCCESS =
    '[DTPS_ENTREE] DTPS_ENTREE_SUCCESS';
export const DTPS_ENTREE_FAILED =
    '[DTPS_ENTREE] DTPS_ENTREE_FAILED';
export const DTPS_ENTREE_IN_PROGRESS =
    '[DTPS_ENTREE] DTPS_ENTREE_IN_PROGRESS';
export const DTPS_ENTREE_INIT =
    '[DTPS_ENTREE] DTPS_ENTREE_INIT';

export const VALIDER_DTPS_ENTREE_REQUEST =
    '[VALIDER_DTPS_ENTREE] VALIDER_DTPS_ENTREE_REQUEST';
export const VALIDER_DTPS_ENTREE_SUCCESS =
    '[VALIDER_DTPS_ENTREE] VALIDER_DTPS_ENTREE_SUCCESS';
export const VALIDER_DTPS_ENTREE_FAILED =
    '[VALIDER_DTPS_ENTREE] VALIDER_DTPS_ENTREE_FAILED';
export const VALIDER_DTPS_ENTREE_IN_PROGRESS =
    '[VALIDER_DTPS_ENTREE] VALIDER_DTPS_ENTREE_IN_PROGRESS';
export const VALIDER_DTPS_ENTREE_INIT =
    '[VALIDER_DTPS_ENTREE] VALIDER_DTPS_ENTREE_INIT';

    