export const CONFIRM_RECONNAISSANCE_REQUEST = '[CONFIRM_RECONNAISSANCE] CONFIRM_RECONNAISSANCE_REQUEST';
export const CONFIRM_RECONNAISSANCE_SUCCESS = '[CONFIRM_RECONNAISSANCE] CONFIRM_RECONNAISSANCE_SUCCESS';
export const CONFIRM_RECONNAISSANCE_FAILED = '[CONFIRM_RECONNAISSANCE] CONFIRM_RECONNAISSANCE_FAILED';
export const CONFIRM_RECONNAISSANCE_IN_PROGRESS = '[CONFIRM_RECONNAISSANCE] CONFIRM_RECONNAISSANCE_IN_PROGRESS';
export const CONFIRM_RECONNAISSANCE_INIT = '[CONFIRM_RECONNAISSANCE] CONFIRM_RECONNAISSANCE_INIT';

export const SEARCH_RECONNAISSANCE_REQUEST = '[SEARCH_RECONNAISSANCE] SEARCH_RECONNAISSANCE_REQUEST';
export const SEARCH_RECONNAISSANCE_SUCCESS = '[SEARCH_RECONNAISSANCE] SEARCH_RECONNAISSANCE_SUCCESS';
export const SEARCH_RECONNAISSANCE_FAILED = '[SEARCH_RECONNAISSANCE] SEARCH_RECONNAISSANCE_FAILED';
export const SEARCH_RECONNAISSANCE_IN_PROGRESS = '[SEARCH_RECONNAISSANCE] SEARCH_RECONNAISSANCE_IN_PROGRESS';
export const SEARCH_RECONNAISSANCE_INIT = '[SEARCH_RECONNAISSANCE] SEARCH_RECONNAISSANCE_INIT';

export const DETAIL_RECONNAISSANCE_REQUEST = '[DETAIL_RECONNAISSANCE] DETAIL_RECONNAISSANCE_REQUEST';
export const DETAIL_RECONNAISSANCE_SUCCESS = '[DETAIL_RECONNAISSANCE] DETAIL_RECONNAISSANCE_SUCCESS';
export const DETAIL_RECONNAISSANCE_FAILED = '[DETAIL_RECONNAISSANCE] DETAIL_RECONNAISSANCE_FAILED';
export const DETAIL_RECONNAISSANCE_IN_PROGRESS = '[DETAIL_RECONNAISSANCE] DETAIL_RECONNAISSANCE_IN_PROGRESS';
export const DETAIL_RECONNAISSANCE_INIT = '[DETAIL_RECONNAISSANCE] DETAIL_RECONNAISSANCE_INIT';
