export const AUTH_LOGIN_REQUEST = '[AUTH] AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = '[AUTH] AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = '[AUTH] AUTH_LOGIN_FAILED';
export const AUTH_LOGIN_IN_PROGRESS = '[AUTH] AUTH_LOGIN_IN_PROGRESS';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const LOGIN_INIT = '[AUTH] LOGIN_INIT';