export const LISTDECLARATION_REQUEST = '[LISTDECLARATION] LISTDECLARATION_REQUEST';
export const LISTDECLARATION_SUCCESS = '[LISTDECLARATION] LISTDECLARATION_SUCCESS';
export const LISTDECLARATION_FAILED = '[LISTDECLARATION] LISTDECLARATION_FAILED';
export const LISTDECLARATION_IN_PROGRESS = '[LISTDECLARATION] LISTDECLARATION_IN_PROGRESS';
export const LISTDECLARATION_INIT = '[LISTDECLARATION] LISTDECLARATION_INIT';