export const SMSVERIFY_REQUEST = '[SMSVERIFY] SMSVERIFY_REQUEST';
export const SMSVERIFY_SUCCESS = '[SMSVERIFY] SMSVERIFY_SUCCESS';
export const SMSVERIFY_FAILED = '[SMSVERIFY] SMSVERIFY_FAILED';
export const SMSVERIFY_IN_PROGRESS = '[SMSVERIFY] SMSVERIFY_IN_PROGRESS';
export const SMSVERIFY_INIT = '[SMSVERIFY] SMSVERIFY_INIT';