export const INIT_APUR_REQUEST = '[INIT_APUR] INIT_APUR_REQUEST';
export const INIT_APUR_SUCCESS = '[INIT_APUR] INIT_APUR_SUCCESS';
export const INIT_APUR_FAILED = '[INIT_APUR] INIT_APUR_FAILED';
export const INIT_APUR_IN_PROGRESS = '[INIT_APUR] INIT_APUR_IN_PROGRESS';
export const INIT_APUR_INIT = '[INIT_APUR] INIT_APUR_INIT';
