export const GENERIC_REQUEST = '[GENERIC] GENERIFC_REQUEST';
export const GENERIC_SUCCESS = '[GENERIC] GENERIC_SUCCESS';
export const GENERIC_FAILED = '[GENERIC] GENERIC_FAILED';
export const GENERIC_IN_PROGRESS = '[GENERIC] GENERIC_IN_PROGRESS';
export const GENERIC_INIT = '[GENERIC] GENERIC_INIT';
export const GENERIC_REFRESH = '[GENERIC] GENERIC_REFRESH';
export const GENERIC_INIT_REFRESH = '[GENERIC] GENERIC_INIT_REFRESH';
export const GENERIC_CATCH_API = '[GENERIC] GENERIC_CATCH_API';

export const GENERIC_REF_REQUEST = '[GENERIC] GENERIC_REF_REQUEST';
export const GENERIC_REF_SUCCESS = '[GENERIC] GENERIC_REF_SUCCESS';
export const GENERIC_REF_FAILED = '[GENERIC] GENERIC_REF_FAILED';
export const GENERIC_REF_IN_PROGRESS = '[GENERIC] GENERIC_REF_IN_PROGRESS';
export const GENERIC_REF_INIT = '[GENERIC] GENERIC_REF_INIT';
