export const ACVP_VALIDATESAVE_REQUEST = '[ACVP] ACVP_VALIDATESAVE_REQUEST';
export const ACVP_VALIDATESAVE_SUCCESS = '[ACVP] ACVP_VALIDATESAVE_SUCCESS';
export const ACVP_VALIDATESAVE_FAILED = '[ACVP] ACVP_VALIDATESAVE_FAILED';
export const ACVP_VALIDATESAVE_IN_PROGRESS = '[ACVP] ACVP_VALIDATESAVE_IN_PROGRESS';
export const ACVP_GENERERCR_REQUEST = '[ACVP] ACVP_GENERERCR_REQUEST';
export const ACVP_GENERERCR_SUCCESS = '[ACVP] ACVP_GENERERCR_SUCCESS';
export const ACVP_GENERERCR_FAILED = '[ACVP] ACVP_GENERERCR_FAILED';
export const ACVP_GENERERCR_IN_PROGRESS = '[ACVP] ACVP_GENERERCR_IN_PROGRESS';