export const CONTROLE_VEHICULE_REQUEST =
  '[CONTROLE_VEHICULE] CONTROLE_VEHICULE_REQUEST';
export const CONTROLE_VEHICULE_SUCCESS =
  '[CONTROLE_VEHICULE] CONTROLE_VEHICULE_SUCCESS';
export const CONTROLE_VEHICULE_FAILED =
  '[CONTROLE_VEHICULE] CONTROLE_VEHICULE_FAILED';
export const CONTROLE_VEHICULE_IN_PROGRESS =
  '[CONTROLE_VEHICULE] CONTROLE_VEHICULE_IN_PROGRESS';
export const CONTROLE_VEHICULE_INIT =
  '[CONTROLE_VEHICULE] CONTROLE_VEHICULE_INIT';

export const status = [
  {code: 'VALIDE', libelle: 'Valide'},
  {code: 'ANNULE', libelle: 'Annulée'},
];
