export const AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_REQUEST = '[GESTION_ECOR_EXPORT] AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_REQUEST';
export const AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_SUCCESS = '[GESTION_ECOR_EXPORT] AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_SUCCES';
export const AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_FAILED = '[GESTION_ECOR_EXPORT] AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_FAILED';
export const AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_IN_PROGRESS = '[GESTION_ECOR_EXPORT] AUTORISER_ACHEMINEMENT_GET_CMB_OPERATEUR_BY_CODE_IN_PROGRESS';

export const AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_REQUEST = '[APPOSITION] AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_REQUEST';
export const AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_SUCCESS = '[APPOSITION] AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_SUCCESS';
export const AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_FAILED = '[APPOSITION] AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_FAILED';
export const AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_IN_PROGRESS =
    '[APPOSITION] AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_IN_PROGRESS';
export const AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_INIT = '[APPOSITION] AUTORISER_ACHEMINEMENT_GET_SCELLES_APPOSEES_INIT';

export const AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_REQUEST = '[APPOSITION] AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_REQUEST';
export const AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_SUCCESS = '[APPOSITION] AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_SUCCESS';
export const AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_FAILED = '[APPOSITION] AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_FAILED';
export const AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_IN_PROGRESS =
    '[APPOSITION] AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_IN_PROGRESS';
export const AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_INIT = '[APPOSITION] AUTORISER_ACHEMINEMENT_IS_REGIME_TRANSBORDEMENT_INIT';

export const AUTORISER_ACHEMINEMENT_UC_REQUEST = '[APPOSITION] AUTORISER_ACHEMINEMENT_UC_REQUEST';
export const AUTORISER_ACHEMINEMENT_UC_SUCCESS = '[APPOSITION] AUTORISER_ACHEMINEMENT_UC_SUCCESS';
export const AUTORISER_ACHEMINEMENT_UC_FAILED = '[APPOSITION] AUTORISER_ACHEMINEMENT_UC_FAILED';
export const AUTORISER_ACHEMINEMENT_UC_IN_PROGRESS =
    '[APPOSITION] AUTORISER_ACHEMINEMENT_UC_IN_PROGRESS';
export const AUTORISER_ACHEMINEMENT_UC_INIT = '[APPOSITION] AUTORISER_ACHEMINEMENT_UC_INIT';


export const APPOSITION_SCELLES_REGIMES_AUTRES_IMPORT = [ "856", "866"];