
export const ETAT_CHARGEMENT_VE_REQUEST =
    '[ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_REQUEST';
export const ETAT_CHARGEMENT_VE_SUCCESS =
    '[ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_SUCCESS';
export const ETAT_CHARGEMENT_VE_FAILED =
    '[ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_FAILED';
export const ETAT_CHARGEMENT_VE_IN_PROGRESS =
    '[ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const ETAT_CHARGEMENT_VE_INIT =
    '[ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_INIT';


export const RECH_IMM_ETAT_CHARGEMENT_VE_REQUEST =
    '[RECH_IMM_ETAT_CHARGEMENT_VE] RECH_IMM_ETAT_CHARGEMENT_VE_REQUEST';
export const RECH_IMM_ETAT_CHARGEMENT_VE_SUCCESS =
    '[RECH_IMM_ETAT_CHARGEMENT_VE] RECH_IMM_ETAT_CHARGEMENT_VE_SUCCESS';
export const RECH_IMM_ETAT_CHARGEMENT_VE_FAILED =
    '[RECH_IMM_ETAT_CHARGEMENT_VE] RECH_IMM_ETAT_CHARGEMENT_VE_FAILED';
export const RECH_IMM_ETAT_CHARGEMENT_VE_IN_PROGRESS =
    '[RECH_IMM_ETAT_CHARGEMENT_VE] RECH_IMM_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const RECH_IMM_ETAT_CHARGEMENT_VE_INIT =
    '[RECH_IMM_ETAT_CHARGEMENT_VE] ETAT_CHARGEMENT_VE_INIT';

export const HISTORIQUE_ETAT_CHARGEMENT_VE_REQUEST =
'[HISTORIQUE_ETAT_CHARGEMENT_VE] HISTORIQUE_ETAT_CHARGEMENT_VE_REQUEST';
export const HISTORIQUE_ETAT_CHARGEMENT_VE_SUCCESS =
'[HISTORIQUE_ETAT_CHARGEMENT_VE] HISTORIQUE_ETAT_CHARGEMENT_VE_SUCCESS';
export const HISTORIQUE_ETAT_CHARGEMENT_VE_FAILED =
'[HISTORIQUE_ETAT_CHARGEMENT_VE] HISTORIQUE_ETAT_CHARGEMENT_VE_FAILED';
export const HISTORIQUE_ETAT_CHARGEMENT_VE_IN_PROGRESS =
'[HISTORIQUE_ETAT_CHARGEMENT_VE] HISTORIQUE_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const HISTORIQUE_ETAT_CHARGEMENT_VE_INIT =
'[HISTORIQUE_ETAT_CHARGEMENT_VE] HISTORIQUE_ETAT_CHARGEMENT_VE_INIT';

export const VERSIONS_ETAT_CHARGEMENT_VE_REQUEST =
'[VERSIONS_ETAT_CHARGEMENT_VE] VERSIONS_ETAT_CHARGEMENT_VE_REQUEST';
export const VERSIONS_ETAT_CHARGEMENT_VE_SUCCESS =
'[VERSIONS_ETAT_CHARGEMENT_VE] VERSIONS_ETAT_CHARGEMENT_VE_SUCCESS';
export const VERSIONS_ETAT_CHARGEMENT_VE_FAILED =
'[VERSIONS_ETAT_CHARGEMENT_VE] VERSIONS_ETAT_CHARGEMENT_VE_FAILED';
export const VERSIONS_ETAT_CHARGEMENT_VE_IN_PROGRESS =
'[VERSIONS_ETAT_CHARGEMENT_VE] VERSIONS_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const VERSIONS_ETAT_CHARGEMENT_VE_INIT =
    '[VERSIONS_ETAT_CHARGEMENT_VE] VERSIONS_ETAT_CHARGEMENT_VE_INIT';

export const SCANNER_ETAT_CHARGEMENT_VE_REQUEST =
    '[SCANNER_ETAT_CHARGEMENT_VE] SCANNER_ETAT_CHARGEMENT_VE_REQUEST';
export const SCANNER_ETAT_CHARGEMENT_VE_SUCCESS =
    '[SCANNER_ETAT_CHARGEMENT_VE] SCANNER_ETAT_CHARGEMENT_VE_SUCCESS';
export const SCANNER_ETAT_CHARGEMENT_VE_FAILED =
    '[SCANNER_ETAT_CHARGEMENT_VE] SCANNER_ETAT_CHARGEMENT_VE_FAILED';
export const SCANNER_ETAT_CHARGEMENT_VE_IN_PROGRESS =
    '[SCANNER_ETAT_CHARGEMENT_VE] SCANNER_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const SCANNER_ETAT_CHARGEMENT_VE_INIT =
    '[SCANNER_ETAT_CHARGEMENT_VE] SCANNER_ETAT_CHARGEMENT_VE_INIT';

export const SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_REQUEST =
    '[SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE] SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_REQUEST';
export const SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_SUCCESS =
    '[SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE] SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_SUCCESS';
export const SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_FAILED =
    '[SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE] SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_FAILED';
export const SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_IN_PROGRESS =
    '[SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE] SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_INIT =
    '[SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE] SCELLES_APRES_SCANNER_ETAT_CHARGEMENT_VE_INIT';

export const INIT_ETAT_CHARGEMENT_VE_REQUEST =
 '[INIT_ETAT_CHARGEMENT_VE] INIT_ETAT_CHARGEMENT_VE_REQUEST';
export const INIT_ETAT_CHARGEMENT_VE_SUCCESS =
'[INIT_ETAT_CHARGEMENT_VE] INIT_ETAT_CHARGEMENT_VE_SUCCESS';
export const INIT_ETAT_CHARGEMENT_VE_FAILED =
'[INIT_ETAT_CHARGEMENT_VE] INIT_ETAT_CHARGEMENT_VE_FAILED';
export const INIT_ETAT_CHARGEMENT_VE_IN_PROGRESS =
'[INIT_ETAT_CHARGEMENT_VE] INIT_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const INIT_ETAT_CHARGEMENT_VE_INIT =
'[INIT_ETAT_CHARGEMENT_VE] INIT_ETAT_CHARGEMENT_VE_INIT';


export const VALIDER_ETAT_CHARGEMENT_VE_REQUEST =
    '[VALIDER_ETAT_CHARGEMENT_VE] VALIDER_ETAT_CHARGEMENT_VE_REQUEST';
export const VALIDER_ETAT_CHARGEMENT_VE_SUCCESS =
    '[VALIDER_ETAT_CHARGEMENT_VE] VALIDER_ETAT_CHARGEMENT_VE_SUCCESS';
export const VALIDER_ETAT_CHARGEMENT_VE_FAILED =
    '[VALIDER_ETAT_CHARGEMENT_VE] VALIDER_ETAT_CHARGEMENT_VE_FAILED';
export const VALIDER_ETAT_CHARGEMENT_VE_IN_PROGRESS =
    '[VALIDER_ETAT_CHARGEMENT_VE] VALIDER_ETAT_CHARGEMENT_VE_IN_PROGRESS';
export const VALIDER_ETAT_CHARGEMENT_VE_INIT =
    '[VALIDER_ETAT_CHARGEMENT_VE] VALIDER_ETAT_CHARGEMENT_VE_INIT';
