export const MAINLEVEE_LISTEDECLARATIONS_REQUEST =
  '[MAINLEVEE] LISTEDECLARATIONS_REQUEST';
export const MAINLEVEE_LISTEDECLARATIONS_SUCCESS =
  '[MAINLEVEE] LISTEDECLARATIONS_SUCCESS';
export const MAINLEVEE_LISTEDECLARATIONS_FAILED =
  '[MAINLEVEE] LISTEDECLARATIONS_FAILED';
export const MAINLEVEE_LISTEDECLARATIONS_IN_PROGRESS =
  '[MAINLEVEE] LISTEDECLARATIONS_IN_PROGRESS';
