export const MAINLEVEE_RECHERCHEDECLARATION_REQUEST = '[MAINLEVEE] RECHERCHEDECLARATION_REQUEST';
export const MAINLEVEE_RECHERCHEDECLARATION_SUCCESS = '[MAINLEVEE] RECHERCHEDECLARATION_SUCCESS';
export const MAINLEVEE_RECHERCHEDECLARATION_FAILED = '[MAINLEVEE] RECHERCHEDECLARATION_FAILED';
export const MAINLEVEE_RECHERCHEDECLARATION_IN_PROGRESS = '[MAINLEVEE] RECHERCHEDECLARATION_IN_PROGRESS';
export const MAINLEVEE_RECHERCHEDECLARATION_INIT = '[MAINLEVEE] MAINLEVEE_RECHERCHEDECLARATION_INIT';