export const MAINLEVEE_RECHERCHEDECLARATION_REQUEST =
  '[MAINLEVEE] RECHERCHEDECLARATION_REQUEST';
export const MAINLEVEE_RECHERCHEDECLARATION_SUCCESS =
  '[MAINLEVEE] RECHERCHEDECLARATION_SUCCESS';
export const MAINLEVEE_RECHERCHEDECLARATION_FAILED =
  '[MAINLEVEE] RECHERCHEDECLARATION_FAILED';
export const MAINLEVEE_RECHERCHEDECLARATION_IN_PROGRESS =
  '[MAINLEVEE] RECHERCHEDECLARATION_IN_PROGRESS';
export const MAINLEVEE_RECHERCHEDECLARATION_INIT =
  '[MAINLEVEE] MAINLEVEE_RECHERCHEDECLARATION_INIT';

export const INIT_ETAT_CHARGEMENT_REQUEST = '[MAINLEVEE] INIT_ETAT_CHARGEMENT_REQUEST';
export const INIT_ETAT_CHARGEMENT_SUCCESS = '[MAINLEVEE] INIT_ETAT_CHARGEMENT_SUCCESS';
export const INIT_ETAT_CHARGEMENT_FAILED = '[MAINLEVEE] INIT_ETAT_CHARGEMENT_FAILED';
export const INIT_ETAT_CHARGEMENT_IN_PROGRESS = '[MAINLEVEE] INIT_ETAT_CHARGEMENT_IN_PROGRESS';
export const INIT_ETAT_CHARGEMENT_INIT = '[MAINLEVEE] INIT_ETAT_CHARGEMENT_INIT';


export const SEARCH_ETAT_CHARGEMENT_REQUEST = '[MAINLEVEE] SEARCH_ETAT_CHARGEMENT_REQUEST';
export const SEARCH_ETAT_CHARGEMENT_SUCCESS = '[MAINLEVEE] SEARCH_ETAT_CHARGEMENT_SUCCESS';
export const SEARCH_ETAT_CHARGEMENT_FAILED = '[MAINLEVEE] SEARCH_ETAT_CHARGEMENT_FAILED';
export const SEARCH_ETAT_CHARGEMENT_IN_PROGRESS = '[MAINLEVEE] SEARCH_ETAT_CHARGEMENT_IN_PROGRESS';
export const SEARCH_ETAT_CHARGEMENT_INIT = '[MAINLEVEE] SEARCH_ETAT_CHARGEMENT_INIT';


export const VALIDATE_ETAT_CHARGEMENT_REQUEST = '[MAINLEVEE] VALIDATE_ETAT_CHARGEMENT_REQUEST';
export const VALIDATE_ETAT_CHARGEMENT_SUCCESS = '[MAINLEVEE] VALIDATE_ETAT_CHARGEMENT_SUCCESS';
export const VALIDATE_ETAT_CHARGEMENT_FAILED = '[MAINLEVEE] VALIDATE_ETAT_CHARGEMENT_FAILED';
export const VALIDATE_ETAT_CHARGEMENT_IN_PROGRESS = '[MAINLEVEE] VALIDATE_ETAT_CHARGEMENT_IN_PROGRESS';
export const VALIDATE_ETAT_CHARGEMENT_INIT = '[MAINLEVEE] VALIDATE_ETAT_CHARGEMENT_INIT';

export const DELIVER_ETAT_CHARGEMENT_REQUEST = '[MAINLEVEE] DELIVER_ETAT_CHARGEMENT_REQUEST';
export const DELIVER_ETAT_CHARGEMENT_SUCCESS = '[MAINLEVEE] DELIVER_ETAT_CHARGEMENT_SUCCESS';
export const DELIVER_ETAT_CHARGEMENT_FAILED = '[MAINLEVEE] DELIVER_ETAT_CHARGEMENT_FAILED';
export const DELIVER_ETAT_CHARGEMENT_IN_PROGRESS = '[MAINLEVEE] DELIVER_ETAT_CHARGEMENT_IN_PROGRESS';
export const DELIVER_ETAT_CHARGEMENT_INIT = '[MAINLEVEE] DELIVER_ETAT_CHARGEMENT_INIT';