export const CONFIRMCNX_DECLARANT_REQUEST = '[CONFIRMCNX] CONFIRMCNX_DECLARANT_REQUEST';
export const CONFIRMCNX_DECLARANT_SUCCESS = '[CONFIRMCNX] CONFIRMCNX_DECLARANT_SUCCESS';
export const CONFIRMCNX_DECLARANT_FAILED = '[CONFIRMCNX] CONFIRMCNX_DECLARANT_FAILED';
export const CONFIRMCNX_DECLARANT_IN_PROGRESS = '[CONFIRMCNX] CONFIRMCNX_DECLARANT_IN_PROGRESS';
export const CONFIRMCNX_DECLARANT_INIT = '[CONFIRMCNX] CONFIRMCNX_DECLARANT_INIT';
