export const INITCONFIRMATIONENTREE_REQUEST =
  '[COMPONENT] INITCONFIRMATIONENTREE_REQUEST';
export const INITCONFIRMATIONENTREE_SUCCESS =
  '[COMPONENT] INITCONFIRMATIONENTREE_SUCCESS';
export const INITCONFIRMATIONENTREE_FAILED =
  '[COMPONENT] INITCONFIRMATIONENTREE_FAILED';
export const INITCONFIRMATIONENTREE_IN_PROGRESS =
  '[COMPONENT] RECHERCHEREFDUM_IN_PROGRESS';
export const INITCONFIRMATIONENTREE_INIT =
  '[COMPONENT] INITCONFIRMATIONENTREE_INIT';

export const INITCONFIRMATIONENTREE_ETATCHARGEMENT_REQUEST =
  '[COMPONENT] INITCONFIRMATIONENTREE_ETATCHARGEMENT_REQUEST';
export const INITCONFIRMATIONENTREE_ETATCHARGEMENT_SUCCESS =
  '[COMPONENT] INITCONFIRMATIONENTREE_ETATCHARGEMENT_SUCCESS';
export const INITCONFIRMATIONENTREE_ETATCHARGEMENT_FAILED =
  '[COMPONENT] INITCONFIRMATIONENTREE_ETATCHARGEMENT_FAILED';
export const INITCONFIRMATIONENTREE_ETATCHARGEMENT_IN_PROGRESS =
  '[COMPONENT] INITCONFIRMATIONENTREE_ETATCHARGEMENT_IN_PROGRESS';
export const INITCONFIRMATIONENTREE_ETATCHARGEMENT_INIT =
  '[COMPONENT] INITCONFIRMATIONENTREE_ETATCHARGEMENT_INIT';

export const INITCONFIRMATIONENTREE_UPDATE_VO =
  '[COMPONENT] INITCONFIRMATIONENTREE_UPDATE_VO';

export const CONFIRMERNTREE_REQUEST = '[ACTION] CONFIRMERNTREE_REQUEST';
export const CONFIRMERNTREE_SUCCESS = '[ACTION] CONFIRMERNTREE_SUCCESS';
export const CONFIRMERNTREE_FAILED = '[ACTION] CONFIRMERNTREE_FAILED';
export const CONFIRMERNTREE_IN_PROGRESS = '[ACTION] CONFIRMERNTREE_IN_PROGRESS';
export const CONFIRMERNTREE_INIT = '[ACTION ] CONFIRMERNTREET_INIT';

export const typeListe = [
  {code: 'etatChargement', libelle: 'Référence Etat de chargement'},
  {code: 'moyenT', libelle: 'Moyen de transport'},
];

export const typeListeAmp = [
  {code: 'immatriculation', libelle: 'Immatriculation'},
  {code: 'numeroAmp', libelle: 'Numéro'},
];
