export const DTPS_CONSULTATION_REQUEST =
    '[DTPS_CONSULTATION] DTPS_CONSULTATION_REQUEST';
export const DTPS_CONSULTATION_SUCCESS =
    '[DTPS_CONSULTATION] DTPS_CONSULTATION_SUCCESS';
export const DTPS_CONSULTATION_FAILED =
    '[DTPS_CONSULTATION] DTPS_CONSULTATION_FAILED';
export const DTPS_CONSULTATION_IN_PROGRESS =
    '[DTPS_CONSULTATION] DTPS_CONSULTATION_IN_PROGRESS';
export const DTPS_CONSULTATION_INIT =
    '[DTPS_CONSULTATION] DTPS_CONSULTATION_INIT';


    