export const ACTIFS_CREATION_REQUEST = '[ACTIFS] CREATION_REQUEST';
export const ACTIFS_CREATION_SUCCESS = '[ACTIFS] CREATION_SUCCESS';
export const ACTIFS_CREATION_FAILED = '[ACTIFS] CREATION_FAILED';
export const ACTIFS_CREATION_IN_PROGRESS = '[ACTIFS] CREATION_IN_PROGRESS';
export const ACTIFS_CREATION_INIT = '[ACTIFS] CREATION_INIT';

export const ACTIFS_DETAILS_REQUEST = '[ACTIFS] DETAILS_REQUEST';
export const ACTIFS_DETAILS_SUCCESS = '[ACTIFS] DETAILS_SUCCESS';
export const ACTIFS_DETAILS_FAILED = '[ACTIFS] DETAILS_FAILED';
export const ACTIFS_DETAILS_IN_PROGRESS = '[ACTIFS] DETAILS_IN_PROGRESS';
export const ACTIFS_DETAILS_INIT = '[ACTIFS] DETAILS_INIT';

export const ACTIFS_ENTETE_REQUEST = '[ACTIFS] ENTETE_REQUEST';
export const ACTIFS_ENTETE_SUCCESS = '[ACTIFS] ENTETE_SUCCESS';
export const ACTIFS_ENTETE_FAILED = '[ACTIFS] ENTETE_FAILED';
export const ACTIFS_ENTETE_IN_PROGRESS = '[ACTIFS] ENTETE_IN_PROGRESS';
export const ACTIFS_ENTETE_INIT = '[ACTIFS] ACTIFS_ENTETE_INIT';

export const ACTIFS_SAISIE_REQUEST = '[ACTIFS] SAISIE_REQUEST';
export const ACTIFS_SAISIE_SUCCESS = '[ACTIFS] SAISIE_SUCCESS';
export const ACTIFS_SAISIE_FAILED = '[ACTIFS] SAISIE_FAILED';
export const ACTIFS_SAISIE_IN_PROGRESS = '[ACTIFS] SAISIE_IN_PROGRESS';
export const ACTIFS_SAISIE_INIT = '[ACTIFS] SAISIE_INIT';

export const ACTIFS_CONFIRMER_EMBARCATION_REQUEST = '[ACTIFS] CONFIRMER_EMBARCATION_REQUEST';
export const ACTIFS_CONFIRMER_EMBARCATION_SUCCESS = '[ACTIFS] CONFIRMER_EMBARCATION_SUCCESS';
export const ACTIFS_CONFIRMER_EMBARCATION_FAILED = '[ACTIFS] CONFIRMER_EMBARCATION_FAILED';
export const ACTIFS_CONFIRMER_EMBARCATION_IN_PROGRESS = '[ACTIFS] CONFIRMER_EMBARCATION_IN_PROGRESS';

export const ACTIFS_INITIER_EMBARCATIONS_TAB_REQUEST = '[ACTIFS] INITIER_EMBARCATIONS_TAB_REQUEST';
export const ACTIFS_INITIER_EMBARCATIONS_TAB_SUCCESS = '[ACTIFS] INITIER_EMBARCATIONS_TAB_SUCCESS';
export const ACTIFS_INITIER_EMBARCATIONS_TAB_FAILED = '[ACTIFS] INITIER_EMBARCATIONS_TAB_FAILED';
export const ACTIFS_INITIER_EMBARCATIONS_TAB_IN_PROGRESS = '[ACTIFS] INITIER_EMBARCATIONS_TAB_IN_PROGRESS';

export const ACTIFS_EDITER_EMBARCATION_REQUEST = '[ACTIFS] EDITER_EMBARCATION_REQUEST';
export const ACTIFS_EDITER_EMBARCATION_SUCCESS = '[ACTIFS] EDITER_EMBARCATION_SUCCESS';
export const ACTIFS_EDITER_EMBARCATION_FAILED = '[ACTIFS] EDITER_EMBARCATION_FAILED';
export const ACTIFS_EDITER_EMBARCATION_IN_PROGRESS = '[ACTIFS] EDITER_EMBARCATION_IN_PROGRESS';

export const ACTIFS_DELETE_EMBARCATION_REQUEST = '[ACTIFS] DELETE_EMBARCATION_REQUEST';
export const ACTIFS_DELETE_EMBARCATION_SUCCESS = '[ACTIFS] DELETE_EMBARCATION_SUCCESS';
export const ACTIFS_DELETE_EMBARCATION_FAILED = '[ACTIFS] DELETE_EMBARCATION_FAILED';
export const ACTIFS_DELETE_EMBARCATION_IN_PROGRESS = '[ACTIFS] DELETE_EMBARCATION_IN_PROGRESS';

export const ACTIFS_RESET_EMBARCATION_REQUEST = '[ACTIFS] RESET_EMBARCATION_REQUEST';
export const ACTIFS_RESET_EMBARCATION_SUCCESS = '[ACTIFS] RESET_EMBARCATION_SUCCESS';
export const ACTIFS_RESET_EMBARCATION_FAILED = '[ACTIFS] RESET_EMBARCATION_FAILED';
export const ACTIFS_RESET_EMBARCATION_IN_PROGRESS = '[ACTIFS] RESET_EMBARCATION_IN_PROGRESS';

export const ACTIFS_CONFIRMER_AVION_PRIVEE_REQUEST = '[ACTIFS] CONFIRMER_AVION_PRIVEE_REQUEST';
export const ACTIFS_CONFIRMER_AVION_PRIVEE_SUCCESS = '[ACTIFS] CONFIRMER_AVION_PRIVEE_SUCCESS';
export const ACTIFS_CONFIRMER_AVION_PRIVEE_FAILED = '[ACTIFS] CONFIRMER_AVION_PRIVEE_FAILED';
export const ACTIFS_CONFIRMER_AVION_PRIVEE_IN_PROGRESS = '[ACTIFS] CONFIRMER_AVION_PRIVEE_IN_PROGRESS';

export const ACTIFS_INITIER_AVIONS_PRIVEES_TAB_REQUEST = '[ACTIFS] INITIER_AVIONS_PRIVEES_TAB_REQUEST';
export const ACTIFS_INITIER_AVIONS_PRIVEES_TAB_SUCCESS = '[ACTIFS] INITIER_AVIONS_PRIVEES_TAB_SUCCESS';
export const ACTIFS_INITIER_AVIONS_PRIVEES_TAB_FAILED = '[ACTIFS] INITIER_AVIONS_PRIVEES_TAB_FAILED';
export const ACTIFS_INITIER_AVIONS_PRIVEES_TAB_IN_PROGRESS = '[ACTIFS] INITIER_AVIONS_PRIVEES_TAB_IN_PROGRESS';

export const ACTIFS_EDITER_AVION_PRIVEE_REQUEST = '[ACTIFS] EDITER_AVION_PRIVEE_REQUEST';
export const ACTIFS_EDITER_AVION_PRIVEE_SUCCESS = '[ACTIFS] EDITER_AVION_PRIVEE_SUCCESS';
export const ACTIFS_EDITER_AVION_PRIVEE_FAILED = '[ACTIFS] EDITER_AVION_PRIVEE_FAILED';
export const ACTIFS_EDITER_AVION_PRIVEE_IN_PROGRESS = '[ACTIFS] EDITER_AVION_PRIVEE_IN_PROGRESS';

export const ACTIFS_DELETE_AVION_PRIVEE_REQUEST = '[ACTIFS] DELETE_AVION_PRIVEE_REQUEST';
export const ACTIFS_DELETE_AVION_PRIVEE_SUCCESS = '[ACTIFS] DELETE_AVION_PRIVEE_SUCCESS';
export const ACTIFS_DELETE_AVION_PRIVEE_FAILED = '[ACTIFS] DELETE_AVION_PRIVEE_FAILED';
export const ACTIFS_DELETE_AVION_PRIVEE_IN_PROGRESS = '[ACTIFS] DELETE_AVION_PRIVEE_IN_PROGRESS';

export const ACTIFS_RESET_AVION_PRIVEE_REQUEST = '[ACTIFS] RESET_AVION_PRIVEE_REQUEST';
export const ACTIFS_RESET_AVION_PRIVEE_SUCCESS = '[ACTIFS] RESET_AVION_PRIVEE_SUCCESS';
export const ACTIFS_RESET_AVION_PRIVEE_FAILED = '[ACTIFS] RESET_AVION_PRIVEE_FAILED';
export const ACTIFS_RESET_AVION_PRIVEE_IN_PROGRESS = '[ACTIFS] RESET_AVION_PRIVEE_IN_PROGRESS';
