export const ACTIFS_CREATION_REQUEST = '[ACTIFS] CREATION_REQUEST';
export const ACTIFS_CREATION_SUCCESS = '[ACTIFS] CREATION_SUCCESS';
export const ACTIFS_CREATION_FAILED = '[ACTIFS] CREATION_FAILED';
export const ACTIFS_CREATION_IN_PROGRESS = '[ACTIFS] CREATION_IN_PROGRESS';
export const ACTIFS_CREATION_INIT = '[ACTIFS] CREATION_INIT';

export const ACTIFS_DETAILS_REQUEST = '[ACTIFS] DETAILS_REQUEST';
export const ACTIFS_DETAILS_SUCCESS = '[ACTIFS] DETAILS_SUCCESS';
export const ACTIFS_DETAILS_FAILED = '[ACTIFS] DETAILS_FAILED';
export const ACTIFS_DETAILS_IN_PROGRESS = '[ACTIFS] DETAILS_IN_PROGRESS';
export const ACTIFS_DETAILS_INIT = '[ACTIFS] DETAILS_INIT';

export const ACTIFS_ENTETE_REQUEST = '[ACTIFS] ENTETE_REQUEST';
export const ACTIFS_ENTETE_SUCCESS = '[ACTIFS] ENTETE_SUCCESS';
export const ACTIFS_ENTETE_FAILED = '[ACTIFS] ENTETE_FAILED';
export const ACTIFS_ENTETE_IN_PROGRESS = '[ACTIFS] ENTETE_IN_PROGRESS';
export const ACTIFS_ENTETE_INIT = '[ACTIFS] ACTIFS_ENTETE_INIT';

export const ACTIFS_SAISIE_REQUEST = '[ACTIFS] SAISIE_REQUEST';
export const ACTIFS_SAISIE_SUCCESS = '[ACTIFS] SAISIE_SUCCESS';
export const ACTIFS_SAISIE_FAILED = '[ACTIFS] SAISIE_FAILED';
export const ACTIFS_SAISIE_IN_PROGRESS = '[ACTIFS] SAISIE_IN_PROGRESS';
export const ACTIFS_SAISIE_INIT = '[ACTIFS] SAISIE_INIT';
