export const ACTIFS_GENERIC_REQUEST = '[GENERIC] ACTIFS_GENERIFC_REQUEST';
export const ACTIFS_GENERIC_SUCCESS = '[GENERIC] ACTIFS_GENERIC_SUCCESS';
export const ACTIFS_GENERIC_FAILED = '[GENERIC] ACTIFS_GENERIC_FAILED';
export const ACTIFS_GENERIC_IN_PROGRESS = '[GENERIC] ACTIFS_GENERIC_IN_PROGRESS';
export const ACTIFS_GENERIC_INIT = '[GENERIC] ACTIFS_GENERIC_INIT';
export const ACTIFS_GENERIC_REFRESH = '[GENERIC] ACTIFS_GENERIC_REFRESH';
export const ACTIFS_GENERIC_INIT_REFRESH = '[GENERIC] ACTIFS_GENERIC_INIT_REFRESH';
export const ACTIFS_GENERIC_CATCH_API = '[GENERIC] ACTIFS_GENERIC_CATCH_API';