export const CONFIRMER_REQUEST = '[VUEMBARQUER] CONFIRMER_REQUEST';
export const CONFIRMER_SUCCESS = '[VUEMBARQUER] CONFIRMER_SUCCESS';
export const CONFIRMER_FAILED = '[VUEMBARQUER] CONFIRMER_FAILED';
export const CONFIRMER_IN_PROGRESS = '[VUEMBARQUER] CONFIRMER_IN_PROGRESS';
export const CONFIRMER_INIT = '[VUEMBARQUER] CONFIRMER_INIT';
