
// constants Recherche declaration Dum
export const DED_INIT_CONTROLE_COMMUN_REQUEST =
    '[DED_INIT_CONTROLE_COMMUN] DED_INIT_CONTROLE_COMMUN_REQUEST';
export const DED_INIT_CONTROLE_COMMUN_SUCCESS =
    '[DED_INIT_CONTROLE_COMMUN] DED_INIT_CONTROLE_COMMUN_SUCCESS';
export const DED_INIT_CONTROLE_COMMUN_FAILED =
    '[DED_INIT_CONTROLE_COMMUN] DED_INIT_CONTROLE_COMMUN_FAILED';
export const DED_INIT_CONTROLE_COMMUN_IN_PROGRESS =
    '[DED_INIT_CONTROLE_COMMUN] DED_INIT_CONTROLE_COMMUN_IN_PROGRESS';
export const DED_INIT_CONTROLE_COMMUN_INIT =
    '[DED_INIT_CONTROLE_COMMUN] DED_INIT_CONTROLE_COMMUN_INIT';




export const DED_INIT_LIST_CONTROLE_COMMUN_REQUEST =
    '[DED_INIT_LIST_CONTROLE_COMMUN] DED_INIT_LIST_CONTROLE_COMMUN_REQUEST';
export const DED_INIT_LIST_CONTROLE_COMMUN_SUCCESS =
    '[DED_INIT_LIST_CONTROLE_COMMUN] DED_INIT_LIST_CONTROLE_COMMUN_SUCCESS';
export const DED_INIT_LIST_CONTROLE_COMMUN_FAILED =
    '[DED_INIT_LIST_CONTROLE_COMMUN] DED_INIT_LIST_CONTROLE_COMMUN_FAILED';
export const DED_INIT_LIST_CONTROLE_COMMUN_IN_PROGRESS =
    '[DED_INIT_LIST_CONTROLE_COMMUN] DED_INIT_LIST_CONTROLE_COMMUN_IN_PROGRESS';
export const DED_INIT_LIST_CONTROLE_COMMUN_INIT =
    '[DED_INIT_LIST_CONTROLE_COMMUN] DED_INIT_LIST_CONTROLE_COMMUN_INIT';
