export const SMSVERIFY_REQUEST = '[SMSVERIFY] SMSVERIFY_REQUEST';
export const SMSVERIFY_SUCCESS = '[SMSVERIFY] SMSVERIFY_SUCCESS';
export const SMSVERIFY_FAILED = '[SMSVERIFY] SMSVERIFY_FAILED';
export const SMSVERIFY_IN_PROGRESS = '[SMSVERIFY] SMSVERIFY_IN_PROGRESS';
export const SMSVERIFY_INIT = '[SMSVERIFY] SMSVERIFY_INIT';

export const GENERERCODESMS_SUCCESS = '[GENERERCODESMS] GENERERCODESMS_SUCCESS';
export const GENERERCODESMS_REQUEST = '[GENERERCODESMS] GENERERCODESMS_REQUEST';
export const GENERERCODESMS_FAILED = '[GENERERCODESMS] GENERERCODESMS_FAILED';
export const GENERERCODESMS_IN_PROGRESS =
  '[GENERERCODESMS] GENERERCODESMS_IN_PROGRESS';
