name: build
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build eslint report for QA
        run: |
          eslint . -f node_modules/eslint-html-reporter/reporter.js -o report.html
      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: /home/runner/work/BadrMobileRn/BadrMobileRn/android/app/build/outputs/apk/debug/

